Sign-in redirect: Change the default redirect to /projects
CoMakery/comakery-server pull request #1692
Opened 2020-09-23 15:30 UTC by Riddlerrr

To fix the bug https://app.asana.com/0/1138839033616420/1192251222542097

It happens because after sign in we redirects to `/tasks` path. But a new user doesn't have any tasks. So we redirect him back to the sign-in page.

So we decided to change the default redirect to `/projects`

2020-09-23 15:43 UTC, Riddlerrr commented
Oh, looks like there are still many tests to fix. Will do it

2020-09-23 15:51 UTC, Riddlerrr commented
Hmm, looks like it's only local error. CI is successfully done

2020-09-23 17:08 UTC, aquabu commented on app/controllers/sessions_controller.rb
> +        projects_path
Just discussed this with @Alexey1100. Lets make this conditional:
* If you have >= 1 project on my projects page it redirects to `/projects/mine`
* If you have 0 projects and missions are not displayed (whitelabel) it redirects to `/projects`
* If you have 0 projects and missions are displayed (CoMakery.com) it redirects to `/` (this will show the same thing as the logged out home page on CoMakery.com)

This behavior works for whitelabel versions without missions on the home page.

2020-09-23 18:45 UTC, Riddlerrr commented
@aquabu @Alexey1100 Could you take a look of the new version?

2020-09-23 18:56 UTC, aquabu commented on app/controllers/sessions_controller.rb
> +        projects_path
@Riddlerrr Is there a good way to get the cyclomatic complexity down?

2020-09-23 18:57 UTC, aquabu approved these changes

2020-09-23 18:58 UTC, aquabu commented
@Riddlerrr looks good. Might be good to get the cyclomatic complexity down - but not a blocking request.

2020-09-23 19:02 UTC, aquabu commented
@Alexey1100 can you review as well?

2020-09-24 05:22 UTC, Riddlerrr commented on app/controllers/sessions_controller.rb
> +        projects_path
@aquabu You are right, better to refactor it =)
Done, looks much better now

2020-09-24 05:25 UTC, aquabu commented on app/controllers/sessions_controller.rb
> +      return redirect_to_my_tasks_with_notice if session[:redeem]
Nice refactor :)

2020-09-24 05:26 UTC, aquabu commented on app/controllers/sessions_controller.rb
> +        projects_path
Nice refactor in the latest commit :)

2020-09-24 16:07 UTC, Alexey1100 requested changes

2020-09-24 16:07 UTC, Alexey1100 commented on app/controllers/sessions_controller.rb
> +      return redirect_to_my_projects if current_account.projects.any?
My Projects page also includes interested, team and archived projects, so I think we would want to redirect there if any of these are present.

(See `app/controllers/projects_controller.rb:20` for reference)

2020-09-29 16:24 UTC, Riddlerrr commented on app/controllers/sessions_controller.rb
> +      return redirect_to_my_projects if current_account.projects.any?
@Alexey1100 Sorry, maybe I didn't understand something.
I see interested and team projects on the `/projects/mine` page.

Do you mean not all of the projects contain in `current_account.projects`?

![image](https://user-images.githubusercontent.com/517356/94584985-0eada180-0288-11eb-8c9d-0b0252f6f011.png)

2020-09-29 16:59 UTC, aquabu commented
ok, this is getting more complicated. Let's go back to the previous functionality:
* When you login to CoMakery.com (not whitelabel) you end up on /tasks
* When you login to the whitelabel you are redirected to /projects/mine

2020-09-29 18:39 UTC, Riddlerrr commented
@Alexey1100 @aquabu Applied the last agreed logic, please take a look.

2020-09-29 18:48 UTC, aquabu commented
Looks good. Just waiting on @Alexey1100 review then will merge.

2020-09-30 16:43 UTC, Alexey1100 approved these changes

2020-09-30 16:51 UTC, merged