TransferController: Re-implement ordering in bypass ransack
CoMakery/comakery-server pull request #1695
Opened 2020-09-25 05:52 UTC by Riddlerrr

To solve the bug https://app.asana.com/0/1138839033616420/1184924517589713/f

Ransack has [an issue](https://github.com/activerecord-hackery/ransack#in-your-controller) with `distinct`.
You can use either distinct or ordering with joins, not at the same time.

After playing a bit with it I decided that the easiest way to solve it is to sort by the custom method and not rely on to ransack.

2020-09-25 05:53 UTC, Riddlerrr commented
@aquabu @Alexey1100 Guys, what do you think?

2020-09-25 06:03 UTC, Riddlerrr commented
There is a security issue. I believe we can fix it by introducing sorting whitelist params

2020-09-25 15:40 UTC, Alexey1100 requested changes

2020-09-25 15:40 UTC, Alexey1100 commented on app/controllers/dashboard/transfers_controller.rb
> +    def order_transfers(transfers)
Looks good.
Would be perfect to extract that into a model concern, accepting custom params, so we can reuse it, and have some specs around it.

2020-09-25 15:40 UTC, Alexey1100 commented on app/controllers/dashboard/transfers_controller.rb
> +      s = params.dig(:q, :s)
Regarding the SQL injection warning, yeah I think we can avoid passing custom strings to query by introducing whitelist or by adding a case statement, which converts provided param to query.

2020-09-25 15:48 UTC, aquabu commented on app/controllers/dashboard/transfers_controller.rb
> +      return ordered_transfers unless s
it would be more self documenting if the `s` param is assigned to a variable with a more descriptive name

2020-10-12 12:50 UTC, Riddlerrr commented on app/models/award.rb
> -  scope :transfer_ready, ->(blockchain) { accepted.joins(account: :wallets).where(wallets: { _blockchain: blockchain }).having('count(wallets) > 0') }
@Alexey1100  Is that having really needed? We already filtered cases without wallets by `inner join`.
I've removed it because it brings me errors.

2020-10-12 16:40 UTC, Alexey1100 commented on app/models/award.rb
> -  scope :transfer_ready, ->(blockchain) { accepted.joins(account: :wallets).where(wallets: { _blockchain: blockchain }).having('count(wallets) > 0') }
Let me check.
We have an additional requirement that account not only should have a wallet, but a wallet with specific blockchain.

2020-10-12 16:45 UTC, Alexey1100 commented on app/models/award.rb
> -  scope :transfer_ready, ->(blockchain) { accepted.joins(account: :wallets).where(wallets: { _blockchain: blockchain }).having('count(wallets) > 0') }
But if specs are passing then the join does job.

2020-10-12 16:50 UTC, Alexey1100 approved these changes

2020-10-12 16:53 UTC, aquabu approved these changes

2020-10-12 16:53 UTC, merged