Algo Security Token transactions parsing
CoMakery/comakery-server pull request #1772
Opened 2020-12-16 17:23 UTC by Alexey1100

- Add tx wrappers
- Update algo app tx wrapper

2020-12-16 18:16 UTC, aquabu commented on app/lib/comakery/algorand/tx/app/security_token/transfer_group_lock.rb
> +nd
needs an `e`

2020-12-17 17:44 UTC, Alexey1100 commented on app/lib/comakery/algorand/tx/app.rb
> +  def to_object(blockchain_transaction)
Thinking about providing `blockchain_transaction` instead of `hash` during initialisation to not pass it around here and in validation calls.
Will require refactoring `Comakery::Algorand::Tx` and `Comakery::Erc20::Tx` along with their calls.

2020-12-28 17:29 UTC, Alexey1100 commented on app/lib/comakery/algorand/tx.rb
> +  def valid?(_)
Keep parameter for consistency with Comakery::Eth::Contract::Erc20::Tx

2020-12-28 17:33 UTC, Alexey1100 commented on app/lib/comakery/algorand/tx/app.rb
> +  def valid?(_)
Keep parameter for consistency with Comakery::Eth::Contract::Erc20::Tx

2021-02-09 22:16 UTC, aquabu commented on app/lib/comakery/algorand/tx.rb
> +  def valid?(_ = nil)
What is this argument used for?

2021-02-09 22:18 UTC, aquabu commented on app/lib/comakery/algorand/tx/app.rb
> +  # Note: Algosinger appArgs format
Algosinger  -> Algosigner

2021-02-09 22:21 UTC, Alexey1100 commented on app/lib/comakery/algorand/tx.rb
> +  def valid?(_ = nil)
@aquabu 

It's left for interface compatibility with `Comakery::Eth::Contract::Erc20::Tx` subclasses (which accept the blockchain transaction during validation rather than initialisation), since `BlockchainTransaction` doesn't know the type when calling the validation (see `BlockchainTransaction#valid_on_chain?`)

2021-02-09 22:24 UTC, aquabu commented on app/lib/comakery/algorand/tx/app/security_token/burn.rb
> +  def app_args
Can these app functions be consolidated into one app class? One class per method seems like it obscures the total app behavior.

2021-02-09 22:29 UTC, aquabu commented on app/lib/comakery/algorand/tx/app/security_token/set_address_permissions.rb
> +      (blockchain_transaction.blockchain_transactable.account_frozen ? 1 : 0),
Non blocking comment. There are a lot of chained methods/associations here. Maybe we should consider refactoring... see the Law of Demeter. For example: https://medium.com/better-programming/demeters-law-don-t-talk-to-strangers-87bb4af11694

2021-02-09 22:40 UTC, Alexey1100 commented on app/lib/comakery/algorand/tx/app/security_token/burn.rb
> +  def app_args
@aquabu each subclass represents a **transaction type** based on action (transfer, asset_transfer, asset_opt_in, app_opt_in, app_transfer, etc.) and inherits from parent type – Burn in this case inherits from a generic app transaction (only having custom app args and app accounts), which itself inherits from Algorand transaction (having custom transaction fields). 
 
Since the purpose of each instance is to validate and generate the transaction (the logic which depends only on the type) I think it's totally make sense to build the hierarchy based on that.

2021-02-09 22:46 UTC, Alexey1100 commented on app/lib/comakery/algorand/tx/app/security_token/set_address_permissions.rb
> +      (blockchain_transaction.blockchain_transactable.account_frozen ? 1 : 0),
I agree, the relationships between BlockchainTransaction, Blockchain and Tx wrapper classes are already asking for refactoring for a while :)

I think we can do it once we finish the Algorand Integration, as we initially planned, so we will have at least two different security tokens implemented.

2021-02-09 22:54 UTC, aquabu requested changes

2021-02-09 22:54 UTC, aquabu commented on app/lib/comakery/algorand/tx/asset.rb
> +  def valid?(_ = nil)
Seems like we are just throwing away any argument here? What's the purpose? Is this because we have to take one argument to implement a `valid?(arg)` interface

2021-02-09 22:54 UTC, aquabu commented on app/models/blockchain_transaction.rb
> +      self.token ||= blockchain_transactable.is_a?(Token) ? blockchain_transactable : blockchain_transactable.token
Seems like we should make the blockchain transactable subclasses polymorphic so we don't have to implement any conditionals based on class here. The if statement should be encapsulated in the object and the objects should have a standard interface. By passing in the object and calling the standard method implementation of the interface it will return the right value.

By doing this it will also lower the cyclomatic complexity of the function.

I was trying to find a succinct example to illustrate. Sand Metz presents a lot of good material on this. Here's a succinct ok explanation:
https://cek.io/blog/2014/05/02/poodr-ch-5/

It's ok to do this in a follow up PR but it should be done.

2021-02-09 22:54 UTC, aquabu commented on app/models/blockchain_transaction_account_token_record.rb
> +      on_chain_eth
Similar to the last comment, this should be handled with polymorphism instead of a conditional statement that switches on type.

2021-02-09 22:54 UTC, aquabu commented on app/models/blockchain_transaction_award.rb
> +  def on_chain # rubocop:todo Metrics/CyclomaticComplexity
Same. This should use polymorphism instead of switching on type.

2021-02-09 22:56 UTC, aquabu commented
@Alexey1100 I made some significant refactoring recommendations. I know this PR is critical so they can be done as fast follow ons. But please consider how to refactor into polymorphic classes instead of switching on type. Also, it seems that the app functions should be in one class instead of many (unless I'm missing something important).

2021-02-09 23:03 UTC, Alexey1100 commented on app/lib/comakery/algorand/tx/asset.rb
> +  def valid?(_ = nil)
Yep, pls see previous response for details.

2021-02-09 23:05 UTC, Alexey1100 commented on app/models/blockchain_transaction.rb
> +      self.token ||= blockchain_transactable.is_a?(Token) ? blockchain_transactable : blockchain_transactable.token
blockchain_transactable is already polymorphic, I think the exception here is that some of the blockchain transactables  belong to token, while some of them are token themselves.

We can avoid this particular condition by adding a token method to token itself, for the interface consistency.

2021-02-09 23:08 UTC, Alexey1100 commented on app/models/blockchain_transaction_account_token_record.rb
> +      on_chain_eth
🤔
While all tx subclasses provide the same interface, we still have to decide somewhere what subclass to load based on Blockchain and BlockchainTransactable properties.

Let me think how can we get rid of the condition, since creating a polymorphic `BlockchainTransaction*` model for each blockchain and transaction type combo seems a bit overkill.

2021-02-09 23:19 UTC, Alexey1100 commented
@aquabu sure, I'll look into ways how to improve the associations between Model and wrappers, there's a couple of optimisations I've mentioned above.

> app functions should be in one class instead of many (unless I'm missing something important).
In our case class represents not an app but a transaction, which needs to be parsed and associated with a record in database.

2021-02-09 23:29 UTC, aquabu commented on app/models/blockchain_transaction_account_token_record.rb
> +      on_chain_eth
Naively speaking the logic would be replaced with `token.on_chain`

Instead of `@on_chain = # conditional statement based on type of token`

2021-02-09 23:29 UTC, Alexey1100 commented on app/models/blockchain_transaction_account_token_record.rb
> +      on_chain_eth
Ohh right, we can partially move the tx wrapper initialiser to the `TokenType#on_chain` and then `BlockchainTransaction` subclass can decide the tx type based on it's own type. 

E.g:

```ruby
# token_type/algorand_security_token.rb
def on_chain_prefix
  "Comakery::Algorand::Tx::App::SecurityToken"
end

# blockchain_transaction_account_token_record.rb
def on_chain_name
  "SetAddressPermissions"
end

# blockchain_transaction.rb
def on_chain
  (token.token_type.on_chain_prefix + on_chain_name).constantize.new(self)
end
```

2021-02-09 23:32 UTC, aquabu commented on app/models/blockchain_transaction.rb
> +      self.token ||= blockchain_transactable.is_a?(Token) ? blockchain_transactable : blockchain_transactable.token
Yes, I think it would be beneficial to encapsulate that. As a user of the object it's preferable to not need to know that detail and write special cases for it.

2021-02-09 23:33 UTC, Alexey1100 commented on app/models/blockchain_transaction_account_token_record.rb
> +      on_chain_eth
@noah we base the condition here on 3 factors:

1) token
2) blockchain_transaction type
3) transfer type, in case if blockchain_transaction type is transfer

2021-02-09 23:36 UTC, aquabu commented on app/lib/comakery/algorand/tx.rb
> +  def valid?(_ = nil)
ok. it's probably worth a comment

2021-02-10 07:24 UTC, Riddlerrr approved these changes
Great work!

2021-02-10 07:24 UTC, Riddlerrr commented on app/controllers/concerns/ore_id_callbacks.rb
> +    session[:sign_ore_id_fallback_state] = @state
👍

2021-02-10 17:31 UTC, Alexey1100 commented
It's a bit hard to manually test the functionality right now, given that we don't allow adding Algorand wallets manually and wallet opt-in view is broken right now.

I'll provide some steps today.

2021-02-10 21:24 UTC, aquabu approved these changes

2021-02-10 21:24 UTC, merged

2021-02-10 23:33 UTC, Alexey1100 commented
Ok, this is how we can test the whole set up right now 😅
We need to set up two accounts, one of them having a set of roles given externally with Algosigner. 

### Contributor account

1. Link OREID
2. Create app `optIn` tx for OREID wallet address **(from Wallets page)**

### Project admin account

1. Link OREID
2. Create app `optIn` tx for OREID wallet address **(from Wallets page)**
3. Create app `setRole` tx for OREID wallet address to give wallet role `7` (Reserve + Transfer Rules + Wallets) **(using Algosigner with contract admin account)**
4. Update admin account reg group on Accounts page
5. Update contributor account reg group on Accounts page
6. Create mint transfer to admin account 
7. Create transfer from admin to contributor account 

#### Creating `setRole` tx with Algosigner:
1. Install the [Algosigner](https://www.purestake.com/technology/algosigner/)
2. Set network to AlgorandTest and import account with contract admin role
2. Go to https://purestake.github.io/algosigner-dapp-example/tx-test/signTesting.html
3. Uncheck `Use Default Tx`, Check `Send Transaction`
4. Click `Pay`
5. Paste following transaction object and submit the tx:

```json
{"type":"appl","from":"IKSNMZFYNMXFBWB2JCPMEC4HT7UECC354UDCKNHQTNKF7WQG3UQW7YZHWA","fee":1000,"firstRound":12141970,"lastRound":12142970,"genesisID":"testnet-v1.0","genesisHash":"SGO1GKSzyE7IEPItTxCByw9x8FmnrCDexi9/cOUJOiI=","appIndex":13997710, "appOnComplete":0, "appArgs": ["Z3JhbnRSb2xlcw==", [7]],"appAccounts": ["IKSNMZFYNMXFBWB2JCPMEC4HT7UECC354UDCKNHQTNKF7WQG3UQW7YZHWA"]}
```

Where:
- `firstRound` and `lastRound` should be less and greater than current blockchain round accordingly
- `from` should be contract admin account imported to Algosigner
- `appAccounts` should contain address of the account we want grant the role to