commented non-existing methods from award migration
CoMakery/comakery-server pull request #1784
Opened 2020-12-28 21:19 UTC by ravi4rails

2021-01-06 17:57 UTC, aquabu commented on db/migrate/20200528155545_init_schema.rb
> +class InitSchema < ActiveRecord::Migration[4.2]
migration version may need to be 6.0

2021-01-08 06:54 UTC, Riddlerrr commented on app/models/account.rb
> -class Account < ApplicationRecord
Why did you change it? Since Rails 5`ApplicationRecord ` is parent  class for models

2021-01-08 07:11 UTC, ravi4rails commented on db/migrate/20200528155545_init_schema.rb
> +class InitSchema < ActiveRecord::Migration[4.2]
@aquabu done

2021-01-08 07:18 UTC, ravi4rails commented on app/models/account.rb
> -class Account < ApplicationRecord
@Riddlerrr I changed this to `ActiveRecord::Base` because after deleting migrations I was getting this error
`TypeError: superclass mismatch for class <ModelName>` for account, authentication and project models. 

and after replacing `ApplicationRecord` with `ActiveRecord::Base` this was solved.

2021-01-08 07:22 UTC, ravi4rails commented on app/models/account.rb
> -class Account < ApplicationRecord
But I just checked again by `ApplicationRecord` as parent class and no errors now. May be this was because I forget to add 
6.0 here `class InitSchema < ActiveRecord::Migration[4.2]`  .

I am pushing this quickly

2021-01-08 07:26 UTC, Riddlerrr commented on app/models/account.rb
> -class Account < ApplicationRecord
👍

2021-01-11 01:43 UTC, aquabu commented on db/migrate/20170116023520_write_new_award_column_values.rb
>  class WriteNewAwardColumnValues < ActiveRecord::Migration[4.2]
It seems like this migration should have been deleted.

2021-01-11 01:48 UTC, aquabu commented on .github/workflows/test.yml
> +
Need to test migrations up with `rake db:migrate` and migration down with `rake db:migrate:down VERSION=`, 

Then test the more common way to create the database for a new install by dropping the db and running `rake db:prepare`

2021-01-11 01:49 UTC, aquabu requested changes
A few requested changes:
* there seems to be one earlier migration that should be deleted
* need CI testing code to test migrations

These are described in the comments.

2021-01-11 07:18 UTC, Riddlerrr commented on Gemfile
> +gem 'squasher'
I think we don't need to include this gem into `Gemfile` because it's one-time usage gem and we don't want to maintain/update it.

2021-01-11 13:56 UTC, ravi4rails commented on Gemfile
> +gem 'squasher'
Yes @Riddlerrr I not needed this anymore

2021-01-11 13:59 UTC, ravi4rails commented on Gemfile
> +gem 'squasher'
removed and pushed

2021-01-11 14:01 UTC, Riddlerrr commented on bin/squasher
> +#!/usr/bin/env ruby
@ravi4rails Don't forget to remove this file too.

2021-01-11 14:01 UTC, ravi4rails commented on .github/workflows/test.yml
> +
yes got this. Just one thing this should be in current branch's test.yml or at acceptance? For now I am doing with current branch's test.yml

2021-01-11 14:37 UTC, ravi4rails commented on bin/squasher
> +#!/usr/bin/env ruby
yup, removed this one too.

2021-01-11 14:39 UTC, ravi4rails commented on db/migrate/20170116023520_write_new_award_column_values.rb
>  class WriteNewAwardColumnValues < ActiveRecord::Migration[4.2]
just kept this because removing this migration will have a merge conflict with acceptance. But added again, I think I need to discuss this you on call.

2021-01-11 15:09 UTC, ravi4rails commented on .github/workflows/test.yml
> +
regarding this command: `rake db:migrate:down VERSION=` any specific version for this?

2021-01-12 06:18 UTC, Riddlerrr commented on .github/workflows/test.yml
> +
> regarding this command: rake db:migrate:down VERSION= any specific version for this?

This command migrates down only one specific migration which you set in `VERSION`.
So if we want to migrate down all existing migrations better to use `rake db:rollback STEP=n` where `n` is the count of all migrations.

You can find `n` by run the command: `bin/rails db:migrate:status | grep -c 'up'`
<img width="997" alt="↣ zsh  sergey@MacBook-Pro-Andronov local  2021-01-12 09-16-39" src="https://user-images.githubusercontent.com/517356/104277028-23204d80-54b7-11eb-864a-8abee2a70b33.png">

2021-01-12 06:20 UTC, aquabu commented on .github/workflows/test.yml
> +
ok 👍

2021-01-12 09:02 UTC, Riddlerrr commented
@ravi4rails I've updated with acceptance branch to avoid conflict.
Also, I've fixed CI tests so I think it's ready to merge.

cc @aquabu

2021-01-12 12:31 UTC, Riddlerrr commented on .github/workflows/test.yml
> +
I think we don't need to test `down` migrations because some of them can be irreversible.

2021-01-12 18:26 UTC, aquabu approved these changes

2021-01-12 18:45 UTC, merged