added whitelable env to app json
CoMakery/comakery-server pull request #1808
Opened 2021-01-10 06:06 UTC by ravi4rails

2021-01-18 12:11 UTC, ravi4rails commented
@Alexey1100 need your assistance in this.

2021-01-19 00:34 UTC, Alexey1100 commented
I think we decided to add an initialiser which will check if whitelabel env variable is set to true.
If so, it creates a whitelabel mission (see mom.rb:667) with domain name extracted from `APP_HOST` variable.
This way all further requests to the instance would be routed to that whitelabel mission.

We might want to add a note into Readme on configuring mission details in rails console, such as name, email, logo, favicon and api keys.
Alternatively we can detect that whitelabel mission is unconfigured and create a simple welcome screen where first-time instance visitor can set all the details above.
(cc: @aquabu)

Let me know if you need any other info (:

2021-01-19 07:02 UTC, Riddlerrr commented
@Alexey1100 Great idea with a new welcome page, I support this 👍 
It should be a separate task of course.

2021-01-19 08:43 UTC, ravi4rails commented
@Alexey1100 you mean `mom.rb:617` right?

2021-01-19 15:02 UTC, Alexey1100 commented
@ravi4rails mom:628 in this branch

2021-01-19 15:28 UTC, ravi4rails commented
ahh, yes got that @Alexey1100

2021-01-20 02:50 UTC, aquabu commented
@Alexey1100 definitely a good idea to have a welcome page for configuring the app. Given our priorities right now I would like to defer implementing the welcome page to later.

@ravi4rails For now if we can auto create a mission with the configuration variables on deployment that would be great.

To make that possible I think you will need to:
* Set the mission whitelabel field to "Enabled"
* If the APP_HOST is present, set the Whitelabel Domain to the APP_HOST value
* Make mission logo and mission image optional fields on the model and on the mission admin edit page. They are currently shown as required on `/missions/:id/edit
* You may need to use default white images of the correct dimensions to keep from breaking page layouts.

Below are some white images to use as default values for the mission. To see them you may need to switch to dark mode in GitHub > Account Settings > Appearance.

## Mission Logo 800px x 800px

![](https://staging.comakery.com/rails/active_storage/postgresql/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSnJkbUZ5YVdGdWRITXZhbWsyZVhKNVpuTXpjR3htTUdOck5ubzNORGN5TldGb2R6Z3dkeTh6WkdRMU4yVTRNRFEzTVROak1UTXhNMkl5TlRRek56TXdPRGcxTTJVMll6YzFOelJqWlRBeFlXRTJNelJrTjJReU9EUm1aR1EyTW1RME5Ea3pORGN3QmpvR1JWUTZFR1JwYzNCdmMybDBhVzl1U1NJNWFXNXNhVzVsT3lCbWFXeGxibUZ0WlQwaU9EQXdMbkJ1WnlJN0lHWnBiR1Z1WVcxbEtqMVZWRVl0T0Njbk9EQXdMbkJ1WndZN0JsUTZFV052Ym5SbGJuUmZkSGx3WlVraURtbHRZV2RsTDNCdVp3WTdCbFE9IiwiZXhwIjoiMjAyMS0wMS0yMFQwMjo0NjozNC44NzZaIiwicHVyIjoiYmxvYl9rZXkifX0=--c06da755699e1c9eb3fb634f5d028c59902aa8da/800.png?content_type=image%2Fpng&disposition=inline%3B+filename%3D%22800.png%22%3B+filename%2A%3DUTF-8%27%27800.png)


## Mission Image 1200px x 800px


![](https://staging.comakery.com/rails/active_storage/postgresql/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSnJkbUZ5YVdGdWRITXZhbWsyZVhKNVpuTXpjR3htTUdOck5ubzNORGN5TldGb2R6Z3dkeTloWkRabFlqVTFaVEJtWmpGa01qQmtOakJpTkRVMlpURmpORGs0TkdVNE1qaGpNakUxTldZeU16Vm1ObUZtTXpVMk9EWmtaR1U1TTJaaE1tSTBPVFZqQmpvR1JWUTZFR1JwYzNCdmMybDBhVzl1U1NJNWFXNXNhVzVsT3lCbWFXeGxibUZ0WlQwaU9EQXdMbkJ1WnlJN0lHWnBiR1Z1WVcxbEtqMVZWRVl0T0Njbk9EQXdMbkJ1WndZN0JsUTZFV052Ym5SbGJuUmZkSGx3WlVraURtbHRZV2RsTDNCdVp3WTdCbFE9IiwiZXhwIjoiMjAyMS0wMS0yMFQwMjo0NzoxMS4yNTRaIiwicHVyIjoiYmxvYl9rZXkifX0=--1aa4f382c0adc90a42464ae86f3479fc1ed2fd05/800.png?content_type=image%2Fpng&disposition=inline%3B+filename%3D%22800.png%22%3B+filename%2A%3DUTF-8%27%27800.png)

2021-01-21 06:01 UTC, aquabu requested changes

2021-01-21 06:01 UTC, aquabu commented on lib/tasks/whitelabel_mission.rake
> +namespace :mission do
@Alexey1100 @Riddlerrr would this default mission be better in db:seed?

I believe we are running `rake db:prepare` after deployment to Heroku with app.json and that task runs:
```
rake db:create 
rake db:seed  
rake db:migrate
```

alternatively, we could just run this by including the script in the [app.json](https://github.com/CoMakery/comakery-server/blob/6b03b88c298a38c18e2dce036bd2f524b3537766/app.json#L8) postdeploy array.

2021-01-21 07:31 UTC, Riddlerrr commented on lib/tasks/whitelabel_mission.rake
> +namespace :mission do
I think better to create the white mission using `postdeploy` in `app.json` file. It should be run only once this way.
Also, I think we can remove running `db:prepare` because we run this on each release: https://github.com/CoMakery/comakery-server/blob/27840d6c0cd428d328bbe8a2588984133a5c48f1/Procfile#L3

But it's should be checked, I not sure it will work on the very first deploy. If my suggestion is true we can just replace
`"postdeploy": "bundle exec rails db:prepare"` to `"postdeploy": "bundle exec rails mission: default_whitelabel_mission"`

2021-01-21 17:20 UTC, ravi4rails commented on lib/tasks/whitelabel_mission.rake
> +namespace :mission do
Yes did that. and this worked.

2021-01-21 17:21 UTC, ravi4rails commented on app.json
> +      "required": true
done

2021-01-21 17:21 UTC, ravi4rails commented on app/controllers/application_controller.rb
> +      puts current_domain
done

2021-02-02 17:16 UTC, closed without merging