Transfer API Wallet Selection
CoMakery/comakery-server pull request #1809
Opened 2021-01-10 15:36 UTC by matjacdev515

Task https://www.pivotaltracker.com/story/show/176238550

2021-01-11 00:13 UTC, aquabu commented on app/models/award.rb
> +  belongs_to :wallet, optional: true
There are two design decisions here:
* I think it's a good idea to denormalize the final recipient wallet address and store it as a string in the award table instead of an association. It may be that only occurs after the blockchain transaction payment is initiated and before then the user can change their primary wallet.
* at minimum the name of the association should indicate if the associated wallet is the the sender or receiver wallet

2021-01-11 01:21 UTC, aquabu commented on app/models/wallet.rb
> +  def mark_another_wallet_as_primary
I'm not sure about the intent of this function.

I would think that `mark_another_wallet_as_primary` would allow the caller to specify another wallet as the primary. This seems to set the earliest wallet as primary as an afterhook. Maybe rename the method to `mark_another_wallet_as_primary_after_primary_wallet_is_destroyed` - a bit long but maybe better.

2021-01-11 01:25 UTC, aquabu commented on app/services/wallet_creator.rb
> +    wallets_params.map do |wallet_params|
`wallets_params.map do |wallet_params|` uses the same name `wallet_params` as the array mapped over and the name of the element in the array.

maybe change to `wallets_params.map do |wallet_param|`

2021-01-11 01:27 UTC, aquabu commented on app/services/wallet_creator.rb
> +      tokens_to_provision = wallet_params.delete(:tokens_to_provision)
it's a little unclear what's happening here... is the wallet_params the array being mapped over? If so, deleting an element from the array being mapped over within the map is unclear. I would recommend keeping track of the errors as a second variable or exiting the loop without `wallet.save` if there's an error.

2021-01-11 01:32 UTC, aquabu commented on db/migrate/20210106184139_add_column_primary_wallet_to_wallets.rb
> +    execute <<-SQL
1) Since there is only one wallet per blockchain network currently, couldn't this just be done by creating the `primary_wallet` with `default:true` in an earlier migration and then in a second commit changing the default to false?

2) Otherwise this should be done as a data migration and be run with `rake data:migrate` instead of `rake db:migrate`. 

I think it's probably better to do it as approach 1.

2021-01-11 01:36 UTC, aquabu requested changes
I added a number of comments to resolve.

2021-01-11 06:41 UTC, Riddlerrr commented on app/models/wallet.rb
> +  def mark_another_wallet_as_primary
I suggest name it `mark_first_wallet_as_primary` because it is exactly what we do in the method

2021-01-11 06:47 UTC, Riddlerrr commented on app/controllers/api/v1/wallets_controller.rb
> +        @wallets.each_with_index.map do |wallet, i|
```suggestion
         @wallets.map.with_index do |wallet, i|
```
It just reads a little bit better

2021-01-11 07:08 UTC, Riddlerrr commented on app/services/wallet_creator.rb
> +      wallet.save if wallet.errors.empty?
I wonder can we just call `account.save` outside the loop to save all changes?

2021-01-11 20:33 UTC, matjacdev515 commented on app/models/award.rb
> +  belongs_to :wallet, optional: true
We already storing the final address inside the BlockchainTransactionAward model in the `destination` field, if I understand correctly

2021-01-11 20:39 UTC, matjacdev515 commented on app/services/wallet_creator.rb
> +    wallets_params.map do |wallet_params|
Not sure that I understand. There two different namings `wallets_params` (plural) and `wallet_params` (singular).

`wallets_params` - array of hashes.
`wallet_params` - Hash, list of attributes per wallet.

`wallet_param` - looks more like a specific attribute, not a set of them

2021-01-11 20:52 UTC, matjacdev515 commented on app/services/wallet_creator.rb
> +      tokens_to_provision = wallet_params.delete(:tokens_to_provision)
`wallets_params` it is an array of params per wallet. I removing `tokens_to_provision`  from a wallet hash, because this attribute can't be passed to `account.wallets.new` and should be processed separately.

> I would recommend keeping track of the errors as a second variable or exiting the loop without `wallet.save` if there's an error.

I can't exit the loop because we need to provide error messages for all the wallets sent in the request. So we shouldn't fail on first. But this is a good idea not to try save particular wallet until we make sure that all the wallets can be saved and get rid of `ActiveRecord::Base.transaction` inside the controller.

2021-01-11 20:58 UTC, matjacdev515 commented on db/migrate/20210106184139_add_column_primary_wallet_to_wallets.rb
> +    execute <<-SQL
Good point

2021-01-11 21:02 UTC, matjacdev515 commented on app/services/wallet_creator.rb
> +    wallets_params.map do |wallet_params|
Maybe we can play with naming little bit to make them look different e.g. `wallets_params` and `wallet_attrs`

2021-01-11 21:11 UTC, matjacdev515 commented on app/services/wallet_creator.rb
> +      wallet.save if wallet.errors.empty?
Will test this in different ways, since we are also building another relation inside a wallet `wallet.wallet_provisions.new` this can be a problem.

2021-01-12 17:54 UTC, aquabu commented on app/models/award.rb
> +  belongs_to :wallet, optional: true
ok - let's rename the association to `recipient_wallet`

2021-01-12 18:49 UTC, aquabu commented on app/services/wallet_creator.rb
> +    wallets_params.map do |wallet_params|
ah, I didn't see the s on wallets_. Yes, more distinct naming would be better.

2021-01-13 03:20 UTC, aquabu approved these changes

2021-01-13 08:53 UTC, Riddlerrr approved these changes
Looks great 👍 
P.S. I didn't look through specs but I believe it is ok too.

2021-01-13 17:48 UTC, merged