AccountTokenRecord: Add wallet relation
CoMakery/comakery-server pull request #1811
Opened 2021-01-11 10:33 UTC by Riddlerrr

We decided to link AccountTokenRecord with wallet instead of Account because we will have the ability to have multiple wallets for blockchain. This change needs to be before we will continue with https://github.com/CoMakery/comakery-server/pull/1804

Also I've added `WalletTransferRule` as an alias for `AccountTokenRecord`. It's preparing for the task: https://www.pivotaltracker.com/story/show/176374185

2021-01-11 18:03 UTC, aquabu commented
Note: this should be merged after the create multiple wallet PR.

2021-01-12 16:14 UTC, aquabu requested changes

2021-01-12 16:14 UTC, aquabu commented on db/data_migrations/20210111085831_fill_wallet_for_account_token_record.rb
> +    AccountTokenRecord.where(wallet: nil).includes(:token, :reg_group).find_each do |atr|
Could you write a test for this?

2021-01-12 17:33 UTC, Riddlerrr commented on db/data_migrations/20210111085831_fill_wallet_for_account_token_record.rb
> +    AccountTokenRecord.where(wallet: nil).includes(:token, :reg_group).find_each do |atr|
🤔 I think we don't have tools to test data migrations
@Alexey1100 Do you have any ideas about how we can add specs the data migration?

2021-01-13 11:27 UTC, Riddlerrr commented on db/data_migrations/20210111085831_fill_wallet_for_account_token_record.rb
> +    AccountTokenRecord.where(wallet: nil).includes(:token, :reg_group).find_each do |atr|
Added tests

2021-01-14 17:10 UTC, Alexey1100 approved these changes

2021-01-14 17:24 UTC, aquabu approved these changes

2021-01-14 17:26 UTC, aquabu approved these changes

2021-01-14 17:26 UTC, merged