Add primary wallet feature to web
CoMakery/comakery-server pull request #1821
Opened 2021-01-15 16:47 UTC by Lerek

2021-01-15 17:12 UTC, Riddlerrr requested changes
Let's also use this new `MakePrimaryWallet` class into `Api::V1::WalletsController#update`:
https://github.com/CoMakery/comakery-server/blob/acceptance/app/controllers/api/v1/wallets_controller.rb#L27

2021-01-15 17:16 UTC, Riddlerrr commented on app/controllers/primaries_controller.rb
> +class PrimariesController < ApplicationController
🤔 I think in this case better to simply add `set_primary` action to `WalletController`
It should improve readability. I can't guess what the controller does just by its name.

2021-01-15 17:22 UTC, Lerek commented on app/controllers/primaries_controller.rb
> +class PrimariesController < ApplicationController
@Riddlerrr maybe then it's better just to rename the controller to `WalletPrimariesController` to keep REST style, what do you think about it?

2021-01-15 17:29 UTC, Riddlerrr commented on app/controllers/primaries_controller.rb
> +class PrimariesController < ApplicationController
I thought about it too but my vote still to `set_primary` action. I don't think REST is so important in this case, it is not an API. And this controller will be always with just one action for sure.

@Alexey1100 What do you think?

2021-01-15 17:50 UTC, Lerek commented on app/controllers/primaries_controller.rb
> +class PrimariesController < ApplicationController
@Riddlerrr nvm, I do not insist :) I will move the logic to new action

2021-01-18 06:03 UTC, Riddlerrr approved these changes
👍  Looks good to me

2021-01-18 06:04 UTC, Riddlerrr commented
@aquabu It is ready to merge

2021-01-18 07:32 UTC, aquabu approved these changes

2021-01-18 07:32 UTC, merged