Feature/validate images content type and size
CoMakery/comakery-server pull request #1822
Opened 2021-01-15 21:35 UTC by swimsoft

- Restrict content_type and size for all attachments
- Add specs for all attachment validations
- Include active_storage_validations for testing the validators
- Generate data-migration to validate existing attachments
- fix offenses
- fix specs

2021-01-18 08:55 UTC, Riddlerrr requested changes

2021-01-18 08:55 UTC, Riddlerrr commented on app/models/mission.rb
> +  validates :image, content_type: %w[image/png image/jpg image/jpeg],
Can we extract those settings into custom validator and reuse it everywhere? Because it's a lot of code duplication.

2021-01-18 08:55 UTC, Riddlerrr commented on db/schema.rb
> +    t.string "country"
Could you revert the schema changes? There are no schema changes in this PR.
Also, looks like you loaded DB when the schema was wrong so I suggest re-create your dev DB with the fresh schema.

2021-01-19 00:15 UTC, Alexey1100 commented on db/data_migrations/20210114220605_validate_attachments.rb
> +          m.send(field).purge if m.send(field).attached? && is_valid?(field)
Should it be?

```suggestion
          m.send(field).purge if m.send(field).attached? && invalid?(field)
```

2021-01-19 00:16 UTC, Alexey1100 commented on db/data_migrations/20210114220605_validate_attachments.rb
> +  def valid?(field)
```suggestion
  def invalid?(field)
```
👀

2021-01-19 00:19 UTC, Alexey1100 commented on app/models/mission.rb
> +  validates :image, content_type: %w[image/png image/jpg image/jpeg],
Yep, and we could move all of the specs into a shared example which accepts list of column names and iterates over it (ref `belongs_to_blockchain_spec.rb:30`)

2021-01-21 15:46 UTC, Alexey1100 approved these changes
👍

2021-01-21 18:32 UTC, Riddlerrr approved these changes
Perfect! 👍

2021-01-21 20:48 UTC, merged