Add uniqueness validation to wallet address
CoMakery/comakery-server pull request #1823
Opened 2021-01-18 14:28 UTC by Lerek

2021-01-18 16:37 UTC, Riddlerrr requested changes
I think this task require adding unique DB index too and check and remove already exists duplicates first.
It can be implemented in one migration.

2021-01-18 17:00 UTC, Lerek commented
@Riddlerrr well, there already could some wallet with the same addres-blockchain exist... Should I create migration to destroy duplicates first?

2021-01-18 17:06 UTC, Riddlerrr commented
Nope, I think will be fine to do it in the same migration. You can just remove duplicates before adding the index in the same migration.
Data migrations will also not fit in this case because it will run _after_ regular migrations but we must ensure what we don't have any duplicates _before_ creating the index.

2021-01-18 19:29 UTC, Lerek commented
@Riddlerrr done, could you please take another look?

2021-01-19 00:59 UTC, Alexey1100 commented on db/migrate/20210118172946_add_address_blockchain_account_index_to_wallets.rb
> +    emove_index :wallets, [:account_id, :address, :_blockchain]
```suggestion
    remove_index :wallets, [:account_id, :address, :_blockchain]
```

2021-01-19 06:43 UTC, Riddlerrr approved these changes
👍

2021-01-19 17:51 UTC, merged