Feature/enable or disable login and sign up with metamask
CoMakery/comakery-server pull request #1830
Opened 2021-01-20 17:02 UTC by swimsoft

- Add metamask_login in required env
- Enable/Disable MetaMask button
 - Enable metamask auth label
- Remove metamask_login from env.required
- Scenario for metamask button
- Fix rubocop

2021-01-20 19:37 UTC, Alexey1100 commented on app/helpers/application_helper.rb
> +    options << 'Metamask' if ENV['METAMASK_LOGIN'].present?
Looks like we need to add the variable into `app.json`

2021-01-21 06:05 UTC, aquabu commented on app/helpers/application_helper.rb
> +    options << 'Metamask' if ENV['METAMASK_LOGIN'].present?
Yes, it should have a default value of false in app.json and be required.

2021-01-21 07:09 UTC, Riddlerrr approved these changes
👍

2021-01-21 20:55 UTC, aquabu requested changes

2021-01-21 20:55 UTC, aquabu commented on app.json
> +    },
I think this should actually be:
```
   "METAMASK_LOGIN": {
      "description": "Enable login and signup with MetaMask",
      "required": true,
      "value": false
    },
```

2021-01-22 07:07 UTC, Riddlerrr approved these changes

2021-01-22 20:39 UTC, aquabu commented
@swimsoft Also, there's a merge conflict to be resolved caused by the merge of another app.json PR.

2021-01-26 17:55 UTC, Riddlerrr commented
@aquabu Looks like it's ready to merge

2021-01-27 02:00 UTC, aquabu approved these changes

2021-01-27 02:00 UTC, merged