Update documentation for Api tokens endpoint
CoMakery/comakery-server pull request #1834
Opened 2021-01-21 14:44 UTC by swimsoft

update documentation for api tokens endpoint

2021-01-21 15:58 UTC, Alexey1100 requested changes

2021-01-21 15:58 UTC, Alexey1100 commented on spec/acceptance/api/v1/21_tokens_spec.rb
> +        explanation 'Returns tokens. Filtering tokens ex: OR operator `q[name_or_symbol_cont]=TokenName`, AND operator `q[name_cont]=TokenName&q[network_eq]=Network`.'
How about adding an example request which uses the filtering (e.g. GET – FILTERING).
This way it would be also covered with the integration specs.

2021-01-25 10:51 UTC, Riddlerrr approved these changes

2021-01-25 17:11 UTC, Alexey1100 approved these changes

2021-01-26 06:27 UTC, aquabu approved these changes

2021-01-26 06:27 UTC, merged