Add recipient_wallet_id to GET transfer response
CoMakery/comakery-server pull request #1839
Opened 2021-01-25 20:06 UTC by Lerek

2021-01-25 20:47 UTC, aquabu requested changes

2021-01-25 20:47 UTC, aquabu commented on app/views/api/v1/transfers/_transfer.json.jbuilder
> +  :recipient_wallet_id,
@Lerek seems like there should be a test that changes and the API should be updated.

2021-01-26 12:26 UTC, Riddlerrr requested changes
What about docs update?

2021-01-28 09:38 UTC, Lerek commented
> What about docs update?

@Riddlerrr done, but now there are a lot of conflicts... maybe it makes sense to add `public/doc/api` folder to gitignore and just generate docs on deployment only?

2021-01-28 09:41 UTC, Riddlerrr commented
@Lerek Yeah, we thought about it too.
But for now just merge the `acceptance` branch into the current one and re-generate docs ones again.

2021-01-28 14:30 UTC, Lerek commented
> @Lerek Yeah, we thought about it too.
> But for now just merge the `acceptance` branch into the current one and re-generate docs ones again.

@Riddlerrr got it, thank you! Done)

2021-01-28 17:43 UTC, Riddlerrr approved these changes

2021-01-29 21:41 UTC, aquabu approved these changes
This looks fine but we are gettin more api doc merge conflicts.

2021-01-30 13:16 UTC, Lerek commented
@aquabu done)

2021-02-01 19:35 UTC, merged