Add wallet recovery public api key to missions
CoMakery/comakery-server pull request #1840
Opened 2021-01-25 20:42 UTC by Lerek

2021-01-26 12:21 UTC, Riddlerrr commented
I think the `wallet_recovery_api_public_key` should be available to set using API only and not available to show/edit using UI.
But let's check with @aquabu

2021-01-26 16:49 UTC, aquabu commented
This is the public key used for signing API requests similar to the Whitelabel API key.

You should be able to add it from the missions page. But it should not be editable after it is posted. Currently you would need to contact a site administrator to change it after it has been posted.

I don't think there is an API endpoint for this and there probably shouldn't be for now.

2021-01-26 18:28 UTC, Alexey1100 commented on app/javascript/components/MissionForm.jsx
> +          value={walletRecoveryApiPublicKey}
```suggestion
          value={walletRecoveryApiPublicKey}
          readOnly={this.props.mission.walletRecoveryApiPublicKey}
```

2021-01-26 18:30 UTC, Alexey1100 requested changes
Should be read-only once set

2021-01-27 02:05 UTC, aquabu commented on app/javascript/components/MissionForm.jsx
> +          value={walletRecoveryApiPublicKey}
Yes and the read only property should be on the model level so the form can't be bypassed.

2021-01-27 12:24 UTC, Lerek commented
@aquabu , @Alexey1100 done, could you take a look again, please?

2021-01-27 17:30 UTC, Riddlerrr requested changes
Let'a add `wallet_recovery_api_public_key` as a readonly attribute for the model. Like we do for example here:
https://github.com/CoMakery/comakery-server/blob/b7aa5316cd70b03051592d841543fee26defcf9a/app/models/reg_group.rb#L15

2021-01-28 09:24 UTC, Lerek commented
> Let'a add `wallet_recovery_api_public_key` as a readonly attribute for the model. Like we do for example here:
> https://github.com/CoMakery/comakery-server/blob/b7aa5316cd70b03051592d841543fee26defcf9a/app/models/reg_group.rb#L15

@Riddlerrr done

2021-01-28 17:06 UTC, Riddlerrr approved these changes

2021-01-29 21:40 UTC, aquabu commented
@Lerek I think this issues are fixed but there's a merge conflict.

2021-01-30 13:16 UTC, Lerek commented
@aquabu done)

2021-02-02 00:36 UTC, Alexey1100 approved these changes

2021-02-02 17:45 UTC, merged