Change gear link to lead to edit_project page
CoMakery/comakery-server pull request #1841
Opened 2021-01-26 08:07 UTC by Lerek

2021-01-26 12:27 UTC, Riddlerrr approved these changes

2021-01-26 16:45 UTC, aquabu requested changes
Please add an integration spec.

2021-01-27 10:09 UTC, Lerek commented
> Please add an integration spec.

@aquabu done

2021-01-27 17:36 UTC, Riddlerrr commented on spec/features/project_discovery/landing_page_spec.rb
> +    page.find_all('a.fa.fa-cog').each do |node|
Do we have multiple projects in this example or just one?

2021-01-27 17:36 UTC, Riddlerrr approved these changes

2021-01-28 09:12 UTC, Lerek commented on spec/features/project_discovery/landing_page_spec.rb
> +    page.find_all('a.fa.fa-cog').each do |node|
@Riddlerrr there are 14 projects :)

2021-01-29 21:36 UTC, aquabu approved these changes

2021-01-29 21:36 UTC, merged