Add email field to form after signuping via metamask
CoMakery/comakery-server pull request #1842
Opened 2021-01-26 08:21 UTC by Lerek

2021-01-26 12:28 UTC, Riddlerrr approved these changes

2021-01-26 16:45 UTC, aquabu requested changes
1. Needs a spec. 
2. This should only be shown after signup with MetaMask because. The other signup processes provide the email on the previous signup page.

2021-01-27 10:10 UTC, Lerek commented
> 1. Needs a spec.
> 2. This should only be shown after signup with MetaMask because. The other signup processes provide the email on the previous signup page.

done

2021-01-27 19:06 UTC, aquabu approved these changes

2021-01-27 19:06 UTC, merged