Update account token record api endpoints
CoMakery/comakery-server pull request #1847
Opened 2021-01-27 15:55 UTC by Lerek

2021-01-27 18:44 UTC, Riddlerrr commented
@Lerek When I looked through your code in the PR I've noticed what our initial task was not well thought out.
You did everything right. We just forgot that that now `account_token_records` can have multiple accounts. It complicates things and we decided to leave only `wallet_id` for `show` and `delete` actions.

Updated:
INDEX /api/v1/tokens/: token_id/account_token_records
INDEX /api/v1/tokens/: token_id/account_token_records?account_id=:account_id
CREATE /api/v1/tokens/: token_id/account_token_records
GET /api/v1/tokens/:token_id/account_token_records/?wallet_id=:wallet_id
DELETE /api/v1/tokens/:token_id/account_token_records/?wallet_id=:wallet_id

2021-01-27 18:45 UTC, Riddlerrr commented
@Alexey1100 Please double check the new URLs above ☝️

2021-01-28 14:48 UTC, Lerek commented
> @Alexey1100 Please double check the new URLs above ☝️

@Riddlerrr okey, I've adjusted to the updated toutes list)

2021-01-29 21:26 UTC, Alexey1100 requested changes
@Lerek I think we need a couple more updates here, as mentioned below.

Also, I noticed that `account-form_controller.js:13` is going to be broken, because it was using AccountTokenRecord API endpoints with project policy auth.

I think the best solution atm would be moving away from using that API endpoint with Metamask and creating a separate controller `project/:id/dashboard/account_token_records` with only one `create` action and `project#edit?` policy, and update the stimulus controller to use that action.

2021-01-29 21:26 UTC, Alexey1100 commented on app/controllers/api/v1/account_token_records_controller.rb
> +      Account.find(account_id)
We are using managed_account_id instead of real one in whitelabel API requests.
So, looks like we need to update this controller as well.

2021-01-29 21:26 UTC, Alexey1100 commented on spec/acceptance/api/v1/16_account_token_records_spec.rb
> -      response_field :updatedAt, 'update timestamp', type: :string
We need to keep response fields reference in the documentation

2021-01-30 12:54 UTC, Lerek commented on spec/acceptance/api/v1/16_account_token_records_spec.rb
> -      response_field :updatedAt, 'update timestamp', type: :string
@Alexey1100 but there is no such endpoint anymore, that's why it's been removed

2021-01-30 12:56 UTC, Lerek commented on app/controllers/api/v1/account_token_records_controller.rb
> +      Account.find(account_id)
@Alexey1100 sorry, seems i'm not following, this portion of code was just a bit refactored and reflects exactly the same logic as it was before. Are you sure here should be changed something, and if so, what exactly?

2021-01-30 13:14 UTC, Lerek commented
> @Lerek I think we need a couple more updates here, as mentioned below.
> 
> Also, I noticed that `account-form_controller.js:13` is going to be broken, because it was using AccountTokenRecord API endpoints with project policy auth.
> 
> I think the best solution atm would be moving away from using that API endpoint with Metamask and adding a `create` action into `Dashboard::AccountsController` with `project#edit?` policy, and update the stimulus controller to use that action.

@Alexey1100 maybe atm it's easier just to update the path passed to the stimulus controller, like I did it here: [changed endpoint](https://github.com/CoMakery/comakery-server/pull/1847/files#diff-2558c3b9a7c17301bf2e76e2b3a8df944d8528bd72b5bbb84c6e12e8880333e5R6)?

2021-01-30 14:46 UTC, Alexey1100 commented
@Lerek The issue is that we also removed project policy auth from the api controller, which is not associated with project anymore and requires a full signature auth.

2021-01-30 14:51 UTC, Alexey1100 commented on spec/acceptance/api/v1/16_account_token_records_spec.rb
> -      response_field :updatedAt, 'update timestamp', type: :string
Yes, we return this fields in INDEX response now.

2021-01-30 14:56 UTC, Alexey1100 commented on app/controllers/api/v1/account_token_records_controller.rb
> +      Account.find(account_id)
@Lerek Yep, it's a bit over complicated for security reasons, but we are using `Account#managed_account_id` instead of real `Account#id` in whitelabel API, you can look at other account-related endpoints for the reference.

Since this endpoint is updated and no longer used by stimulus controller, we should switch to `managed_account_id ` here as well.
We don't expose the real account id anywhere else, so it was a bit tricky to use this endpoint from API user perspective.

2021-02-01 19:31 UTC, Lerek commented
@Alexey1100 done

2021-02-02 00:33 UTC, Alexey1100 approved these changes
👍

2021-02-02 19:26 UTC, merged