Feature/api endpoint create hot wallet address
CoMakery/comakery-server pull request #1848
Opened 2021-01-27 17:28 UTC by swimsoft

- Create endpoint to register hot wallet address with a project
- Fix offenses
- Generate new documentation
- Change authorization. update specs
- Fix specs
- Fix conflicts

2021-01-28 01:14 UTC, aquabu requested changes

2021-01-28 01:14 UTC, aquabu commented on app/controllers/api/v1/hot_wallet_addresses_controller.rb
> +      @build_hot_wallet ||= project.create_hot_wallet(wallet_params)
The method name build seems like it implies building the object in memory but not persisting it to the database? It seems like the `build_hot_wallet` and `project.create_hot_wallet` method names should match. They also should be named `build_not_wallet` if only in memory or `create_hot_wallet` when persisted to the database.

2021-01-28 01:14 UTC, aquabu commented on spec/controllers/api/v1/hot_wallet_addresses_controller_spec.rb
> +    context 'when project has assign a hot wallet' do
Minor typo:
'when project already has an assigned hot wallet'

2021-01-28 17:40 UTC, Riddlerrr commented on app/controllers/api/v1/hot_wallet_addresses_controller.rb
> +    @build_hot_wallet.source = Wallet.sources[:hot_wallet]
minor comment:
`@build_hot_wallet.source = :hot_wallet`?

2021-01-28 20:23 UTC, swimsoft commented on app/controllers/api/v1/hot_wallet_addresses_controller.rb
> +    @build_hot_wallet.source = Wallet.sources[:hot_wallet]
👍

2021-01-28 20:30 UTC, swimsoft commented on app/controllers/api/v1/hot_wallet_addresses_controller.rb
> +    @build_hot_wallet.source = Wallet.sources[:hot_wallet]
👍

2021-01-29 21:43 UTC, aquabu commented on app/controllers/api/v1/hot_wallet_addresses_controller.rb
> +      @build_hot_wallet ||= project.create_hot_wallet(wallet_params)
@swimsoft I'm going to merge this but could you create a follow up commit that addresses this naming issue? Thanks.

2021-01-29 21:44 UTC, aquabu approved these changes

2021-01-29 21:44 UTC, merged