Integrate Turbo & Dynamically update transfers table
CoMakery/comakery-server pull request #1854
Opened 2021-01-29 17:03 UTC by matjacdev515

2021-02-03 00:24 UTC, Alexey1100 commented on app/javascript/controllers/account-form_controller.js
> +    this.formTarget.requestSubmit()
👍

So, the logic is triggered and turbo frame got updated after the tx submitted to blockchain, right?

2021-02-03 00:28 UTC, Alexey1100 commented on app/views/dashboard/accounts/_account.html.erb
> +<% form_url = last_record ? project_dashboard_account_path(@project, account) : root_path %>
There was some controller refactoring regarding the way account token records are created recently.
Pls merge acceptance and update the urls.

2021-02-03 00:28 UTC, Alexey1100 commented on app/views/dashboard/accounts/_account.html.erb
>  <% form_data = last_record ? { controller: "account-form", target: "account-form.form", 'account-form-address' => account.address_for_blockchain(@project.token._blockchain), 'account-form-account-id'
`api_v1_project_account_token_records_path ` is no longer available

2021-02-03 00:29 UTC, Alexey1100 commented on app/views/tokens/new.html.erb
> +<%= react_component('TokenForm', @props, prerender: false) %>
Is there some issues with pre rendering this component?

2021-02-03 00:33 UTC, Alexey1100 requested changes
@matjacdev515 Great work!
Pls merge acceptance and check that the account token record creation logic with Metamask is still works properly, since there were some critical updates recently.

Tests for that are running externally by @miemar and not currently included in the repo (since they require complicated setup with browser extension and local blockchain node), so it might be broken even if CI passes.

2021-02-03 10:24 UTC, matjacdev515 commented on app/javascript/controllers/account-form_controller.js
> +    this.formTarget.requestSubmit()
Yes, Turbo triggers only on a form submit or clicking a link

2021-02-03 10:25 UTC, matjacdev515 commented on app/views/dashboard/accounts/_account.html.erb
>  <% form_data = last_record ? { controller: "account-form", target: "account-form.form", 'account-form-address' => account.address_for_blockchain(@project.token._blockchain), 'account-form-account-id'
It is not API)

2021-02-03 10:25 UTC, matjacdev515 commented on app/views/tokens/new.html.erb
> +<%= react_component('TokenForm', @props, prerender: false) %>
Yes, `render component:` not working with Turbo

2021-02-03 15:52 UTC, matjacdev515 commented on app/views/dashboard/accounts/_account.html.erb
>  <% form_data = last_record ? { controller: "account-form", target: "account-form.form", 'account-form-address' => account.address_for_blockchain(@project.token._blockchain), 'account-form-account-id'
@Alexey1100 it was changed to `project_dashboard_accounts_path`. But since it is not a API controller, this form rejected by CSRF because we still submitting it in `account-form_controller.js` by JS

```
Started POST "/projects/6/dashboard/accounts?token_id=7" for 172.22.0.1 at 2021-02-03 15:42:10 +0000
Cannot render console from 172.22.0.1! Allowed networks: 127.0.0.0/127.255.255.255, ::1
Processing by Dashboard::AccountsController#create as */*
  Parameters: {"body"=>{"data"=>{"account_token_record"=>{"max_balance"=>"0", "lockup_until"=>"1609545600", "reg_group_id"=>"0", "account_frozen"=>"true", "account_id"=>"1"}}}, "token_id"=>"7", "project_id"=>"6", "account"=>{}}
Can't verify CSRF token authenticity.
Completed 422 Unprocessable Entity in 2ms (ActiveRecord: 0.0ms | Allocations: 673)
```

Not sure in which way it should be fixed because it is not related to my changes

2021-02-03 17:44 UTC, Alexey1100 commented on app/views/dashboard/accounts/_account.html.erb
>  <% form_data = last_record ? { controller: "account-form", target: "account-form.form", 'account-form-address' => account.address_for_blockchain(@project.token._blockchain), 'account-form-account-id'
I think we have two options:
1) Disable CSRF check for the endpoint
2) Generate CSRF token in the stimulus controller

2021-02-03 17:45 UTC, Alexey1100 commented on app/views/tokens/new.html.erb
> +<%= react_component('TokenForm', @props, prerender: false) %>
Seems like on other pages it works fine

2021-02-04 17:55 UTC, matjacdev515 commented on app/views/tokens/new.html.erb
> +<%= react_component('TokenForm', @props, prerender: false) %>
Turbo sends specific Content-Type, something like `turbo-stream/html` which `render component:` doesn't know how to render and returns empty response.

2021-02-04 17:59 UTC, matjacdev515 commented on app/views/tokens/new.html.erb
> +<%= react_component('TokenForm', @props, prerender: false) %>
Sorry, I misunderstood.  `prerender: false` there because initially it was set `prerender: false` in the controller. So I didn't change anything. I'm not tested if prerender will work because this PR already has lost of changes and it's not really related to its subject.

2021-02-10 19:40 UTC, Alexey1100 approved these changes

2021-02-11 17:27 UTC, aquabu commented on spec/features/pages/featured_spec.rb
> +    sleep 10
@matjacdev515 I think this sleep and the save page needs to be taken out of the spec.

2021-02-11 17:28 UTC, aquabu approved these changes

2021-02-11 17:28 UTC, merged