Hot wallet: Generate and register a new algorand wallet
CoMakery/comakery-server pull request #1857
Opened 2021-02-02 12:51 UTC by Riddlerrr

Task: https://www.pivotaltracker.com/story/show/176550109

2021-02-06 01:22 UTC, aquabu requested changes

2021-02-06 01:22 UTC, aquabu commented on hotwallet/.env.required
> +PROJECT_ID=5
seems like this should be a `.env.example` file and that the actual values shouldn't be checked in?

2021-02-06 01:22 UTC, aquabu commented on hotwallet/app.js
> +function isAllVariablesSet() {
rename to `areAllVariablesSet()` or `checkAllVariablesAreSet()`

2021-02-06 01:22 UTC, aquabu commented on hotwallet/app.js
> +require('dotenv').config()
This is critical code so it needs testing - probably in Jest.

2021-02-08 19:05 UTC, aquabu approved these changes

2021-02-09 00:12 UTC, Alexey1100 commented on hotwallet/lib/hotwalletUtils.js
> +exports.generateAlgorandKeyPair = function generateAlgorandKeyPair() {
Seems like duplicate of `hotwallet/app.js:18`

2021-02-11 17:00 UTC, aquabu approved these changes

2021-02-11 17:00 UTC, merged