Fix issue on register hot wallet address api
CoMakery/comakery-server pull request #1859
Opened 2021-02-02 13:35 UTC by swimsoft

Task: https://www.pivotaltracker.com/story/show/176550376

1. Add project_id key to wallets table
2. Revert the changes on projects table
3. Validate project_id to be assigned only if source is hot_wallet

2021-02-02 19:34 UTC, aquabu commented
@swimsoft there's a merge conflict to resolve on this.

2021-02-02 23:34 UTC, Alexey1100 commented on app/models/project.rb
>    belongs_to :account, touch: true
Let's add `optional: true` here as well so it will be clear, and afaik default behaviour since rails 5 requires that.
We are probably using 4.x config, that's why it currently works.

2021-02-02 23:35 UTC, Alexey1100 commented on app/models/wallet.rb
>    belongs_to :account
Let's add optional: true here so it will be clear, and afaik default behaviour since rails 5 requires that.
We are probably using 4.x config, that's why it currently works.

2021-02-02 23:38 UTC, Alexey1100 commented on app/models/wallet.rb
> +  def validate_project_id
And we need to extend the validation here, to check that either account or project ids are present, depending on source.

2021-02-02 23:42 UTC, Alexey1100 requested changes
Wallet validation logic updates

2021-02-03 17:49 UTC, Alexey1100 approved these changes

2021-02-03 20:57 UTC, aquabu approved these changes

2021-02-03 20:58 UTC, merged