Feature/transfer page chart balances display correctly
CoMakery/comakery-server pull request #1867
Opened 2021-02-05 17:02 UTC by swimsoft

Task: https://www.pivotaltracker.com/story/show/175048818

Fix matching colors
Add migration to fix source for awards
Rename Transfer Type to Category
Fix chart to support negative values

2021-02-06 01:07 UTC, aquabu commented on app/controllers/dashboard/transfers_controller.rb
> +    # TODO: I am using source to filter transfers but before source was set by default earned for all transfer types, is any logic behind?
Tasks use the same model as transfers. Tasks have a default transfer type of earned. Please remove the comment in a future PR if the question is resolved.

2021-02-06 01:10 UTC, aquabu commented on app/decorators/project_decorator.rb
> +        set.group_by(&:transfer_type).map { |k, v| [k.name, negative ? -v.sum(&:total_amount) : v.sum(&:total_amount)] }.to_h.merge(
This should probably be refactored into a separate function with it's own unit test to reduce cyclomatic complexity and increase reliability.

2021-02-06 01:11 UTC, aquabu commented on app/decorators/project_decorator.rb
> +      (10.years.ago.year..Time.current.year).map { |k| transfers_chart_types.merge(timeframe: k.to_s, i: DateTime.strptime(k.to_s, '%Y').to_i) },
Seems like this should be refactored into it's own separate function with it's own unit test.

2021-02-06 01:14 UTC, aquabu requested changes

2021-02-06 01:14 UTC, aquabu commented on db/data_migrations/20210205131554_fix_source_for_awards.rb
> +      award.update(:source, Award.sources[award.transfer_type.name.to_sym] || 0)
What is the function of this? It also should have a test.

2021-02-06 01:14 UTC, aquabu commented on app/lib/comakery/chart_colors.rb
> +  # TODO: Check colors if are ordered correctly
Please check this and remove the TODO.

2021-02-08 17:21 UTC, swimsoft commented on db/data_migrations/20210205131554_fix_source_for_awards.rb
> +      award.update(:source, Award.sources[award.transfer_type.name.to_sym] || 0)
When we create new transfer ex: burn the source is set by default earned. is it a bug or should it be by default earned? that's why I created the migration to fix source for all transfers.

2021-02-08 17:43 UTC, matjacdev515 requested changes

2021-02-08 17:43 UTC, matjacdev515 commented on app/controllers/dashboard/transfers_controller.rb
> +      @transfers_unfiltered = @transfers_unfiltered.not_burned unless transfer_type_name == 'burn'
Think we can avoid unless here by `if transfer_type_name != 'burn'`

2021-02-08 17:43 UTC, matjacdev515 commented on app/controllers/dashboard/transfers_controller.rb
> +      @transfer_type_name ||= TransferType.find_by(id: params.fetch(:q, {}).fetch(:transfer_type_id_eq, nil))&.name
TransferType.find_by(id: params.dig(:q, :transfer_type_id_eq))&.name

2021-02-08 17:43 UTC, matjacdev515 commented on app/decorators/project_decorator.rb
> +    return -amount if negative
Think this whole method can be replaced with simple`number.abs`

2021-02-08 17:43 UTC, matjacdev515 commented on db/data_migrations/20210205131554_fix_source_for_awards.rb
> +      award.update(:source, Award.sources[award.transfer_type.name.to_sym] || 0)
Can we use `update_column` instead?

2021-02-08 17:43 UTC, matjacdev515 commented on app/controllers/dashboard/transfers_controller.rb
> +    @transfer.source = Award.sources[name.to_sym] || 0
You can do `Award.sources[name.to_sym].to_i`

2021-02-08 17:47 UTC, matjacdev515 commented on app/decorators/project_decorator.rb
> +    return -amount if negative
https://ruby-doc.org/core-2.5.0/Numeric.html#method-i-abs

2021-02-08 17:50 UTC, matjacdev515 commented on app/decorators/project_decorator.rb
> +    return -amount if negative
NVM

2021-02-08 19:39 UTC, Alexey1100 commented on db/data_migrations/20210205131554_fix_source_for_awards.rb
> +      award.update(:source, Award.sources[award.transfer_type.name.to_sym] || 0)
Yes, source shouldn't be used anymore after we implemented the transfer types and had the migration below, but looks like there's still some code which sets the source.

https://github.com/CoMakery/comakery-server/blob/d86b5d673e8520d09632d91217cf6b0f157e6a28/db/data_migrations/20200703123332_migrate_award_source_to_transfer_type.rb#L7

2021-02-09 13:10 UTC, swimsoft commented on app/controllers/dashboard/transfers_controller.rb
> +      @transfers_unfiltered = @transfers_unfiltered.not_burned unless transfer_type_name == 'burn'
I used update because using **update_column** skips validations
unless is the opposite of if what's the point to avoid it?

2021-02-09 13:22 UTC, swimsoft commented on db/data_migrations/20210205131554_fix_source_for_awards.rb
> +      award.update(:source, Award.sources[award.transfer_type.name.to_sym] || 0)
> Can we use `update_column` instead?

I used update because using update_column skips validations

2021-02-09 19:37 UTC, aquabu commented on db/data_migrations/20210205131554_fix_source_for_awards.rb
> +      award.update(:source, Award.sources[award.transfer_type.name.to_sym] || 0)
Probably better to include validations and also try running the migrations against demo server data locally.

2021-02-09 23:35 UTC, matjacdev515 approved these changes

2021-02-10 18:26 UTC, aquabu approved these changes

2021-02-10 18:26 UTC, merged