add docs to gitignore
CoMakery/comakery-server pull request #1874
Opened 2021-02-10 16:06 UTC by swimsoft

Task: https://www.pivotaltracker.com/story/show/176797002

2021-02-10 17:44 UTC, Riddlerrr commented on config.ru
> +system('RAILS_ENV=test bundle exec rake docs:generate &') if Rails.env.development?
Is the command will be run on each call? For example, if you run `bundle exec rails console` it will generate docs before start?

2021-02-10 17:47 UTC, Alexey1100 requested changes
Should run on every deploy

2021-02-10 17:47 UTC, Alexey1100 commented on app.json
> +    "postdeploy": "bundle exec rails whitelabel_mission:create_default && bundle exec bin/docs"
I think post deploy runs only once, when Heroku app has been deployed from the `app.json`.

We need to add the logic into `bin/after_deploy_script` when we have all the migrations, so it will work properly.

2021-02-11 01:01 UTC, Alexey1100 commented on bin/after_deploy_script
> +system! 'RAILS_ENV=test bundle exec rake docs:generate'
👍

Let's use bin/rails for consistency with other calls in the script
```suggestion
system! 'bin/rails docs:generate'
```

2021-02-11 01:03 UTC, Alexey1100 approved these changes

2021-02-11 17:24 UTC, Riddlerrr approved these changes

2021-02-12 06:32 UTC, aquabu approved these changes

2021-02-12 06:33 UTC, merged