Feature/parallelize rspec tests
CoMakery/comakery-server pull request #1928
Opened 2021-03-11 12:55 UTC by matjacdev515

2021-03-22 20:36 UTC, Alexey1100 commented on knapsack_rspec_report.json
> +{
Looks like this should be in .gitignore

2021-03-23 01:29 UTC, aquabu commented
# Speed

Looks like its running at around 10m with Knapsack pro. It may rebalance tests to faster speed. If we could cache pre-compilation it would speed up by another 3 min.

# Code Coverage

Seems like it's not writing the entire coverage out to the rcov artifact file. Needs to do that and verify that test coverage is at 98%.

2021-03-23 01:33 UTC, aquabu requested changes
I merged in the 15x parallelism for knapsack. We may be able to speed the build up in future commits by caching asset compilation.

To complete this PR though it needs to aggregate all the coverage data and fail if the coverage is < 98% for the full run.

2021-03-23 01:45 UTC, aquabu commented
I made the build info public to make it easier to debug: https://knapsackpro.com/dashboard/organizations/2193/projects/1396/test_suites/1992/builds

2021-03-25 05:42 UTC, aquabu approved these changes
Merging this to get the test speed improvements. We can add the test coverage in a follow on PR. I'll create a task for it.

2021-03-25 05:42 UTC, merged