Issue#1933
CoMakery/comakery-server pull request #1936
Opened 2021-03-18 07:18 UTC by shoaibmalik786

2021-03-18 10:44 UTC, Riddlerrr commented
The main issue was not fixed and probably got even worse:
The transfers page loads more than 11 minutes 😱 for only 15 transfers
<img width="1132" alt="↣ puma  sergey@MacBook-Pro-Andronov local  2021-03-18 13-31-40" src="https://user-images.githubusercontent.com/517356/111612792-e3475080-87ee-11eb-8b39-da70ce77ac04.png">
There are some huge SQL queries that take ~ 3 minutes each:
<img width="1918" alt="↣ puma  sergey@MacBook-Pro-Andronov local  2021-03-18 13-37-05" src="https://user-images.githubusercontent.com/517356/111613121-3e794300-87ef-11eb-88e9-7d3917dfeed0.png">

I'm still don't know the actual reason why it happens

To compare: the same page in `acceptance` branch loads much faster:
<img width="1369" alt="↣ puma  sergey@MacBook-Pro-Andronov local  2021-03-18 13-02-19" src="https://user-images.githubusercontent.com/517356/111613883-0c1c1580-87f0-11eb-89bc-dc9515152acf.png">

2021-03-18 11:16 UTC, Riddlerrr commented
Ok, looks like I found the reason. 
This line adds too many includes and ActiveRecord going crazy:
https://github.com/CoMakery/comakery-server/blob/8251a06066e58061b70c10eb0c114329841c48a5/app/controllers/dashboard/transfers_controller.rb#L63

In views we do `@transfers_all.sum(:something)` and it generates a big query.
When I disabled it we have a lot of N+1 queries but the page loads fast.

I suggest introducing a separate `@transfers_totals` var which will contain all the sums results we need
And leave `@transfers_all` with includes that are really needed

2021-03-18 12:12 UTC, shoaibmalik786 commented
ok

2021-03-18 16:54 UTC, aquabu commented
Converting this to draft until it's ready to merge. Thanks!

2021-03-23 06:06 UTC, aquabu commented
@Riddlerrr can you review this one?

2021-03-23 07:20 UTC, Riddlerrr commented
@shoaibmalik786 The transfer page itself loads fast now which is great 👍
<img width="965" alt="↣ puma  sergey@MacBook-Pro-Andronov local  2021-03-23 10-05-27" src="https://user-images.githubusercontent.com/517356/112107241-bcf32d80-8bbf-11eb-8078-2dae8df22721.png">

But when it triggers a chart data it still takes ages:
<img width="1128" alt="↣ puma  sergey@MacBook-Pro-Andronov local  2021-03-23 10-09-40" src="https://user-images.githubusercontent.com/517356/112107619-3c80fc80-8bc0-11eb-9f72-7ca7e8b950b6.png">

I found a few more places with SQL problems:
1. https://github.com/CoMakery/comakery-server/blob/6155d43cc52f7d7f078c8dddbdd11e6fda5e9f3b/app/decorators/project_decorator.rb#L184
2. https://github.com/CoMakery/comakery-server/blob/6155d43cc52f7d7f078c8dddbdd11e6fda5e9f3b/app/decorators/project_decorator.rb#L242

2021-03-23 07:26 UTC, Riddlerrr requested changes
see my comment above

2021-03-24 07:07 UTC, mohdsameer commented
@Riddlerrr I have done the required changes. I have not sufficient data to test. so please test and provide your feedback.

2021-03-24 10:14 UTC, Riddlerrr commented
@mohdsameer Now the page loads great 👍

Transfer page:
```
Completed 200 OK in 1252ms (Views: 1131.4ms | ActiveRecord: 60.5ms | Allocations: 627354)
```

chart's lazy loading:
```
Completed 200 OK in 615ms (Views: 328.0ms | ActiveRecord: 148.0ms | Allocations: 190219)
```

I'll review the whole code later today.

2021-03-24 18:13 UTC, zhinfuhnya approved these changes

2021-03-25 05:43 UTC, aquabu commented
@Riddlerrr if you could finish the review on this I will merge it.

2021-03-25 06:21 UTC, Riddlerrr approved these changes

2021-03-25 06:21 UTC, Riddlerrr commented on app/javascript/components/TransfersCalendar.jsx
> +      //Turbo.visit(currentUrl)
Why Turbo was disabled here?

P.S. It's not blocking, I just curious

2021-03-25 06:36 UTC, aquabu commented on app/javascript/components/TransfersCalendar.jsx
> +      //Turbo.visit(currentUrl)
I'm merging since there are no blocks... but thats a good discussion @Riddlerrr @shoaibmalik786

2021-03-25 06:36 UTC, merged