Recaptcha
CoMakery/comakery-server pull request #1950
Opened 2021-03-22 14:30 UTC by kolishchak

2021-03-22 17:02 UTC, Riddlerrr requested changes

2021-03-22 17:02 UTC, Riddlerrr commented on hotwallet/.env.example
> +RECAPTCHA_SITE_KEY=6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
This file used for Hot Wallet. It's a separate service. Could you delete those ENVs from that file?

2021-03-22 17:03 UTC, Riddlerrr commented
@kolishchak Could you run `bin/rubocop` to fix linter issues.

2021-03-22 20:30 UTC, Alexey1100 requested changes

2021-03-22 20:30 UTC, Alexey1100 commented on spec/controllers/sessions_controller_spec.rb
> +    before { allow_any_instance_of(RecaptchaVerifier).to receive(:valid?).and_return(true) }
Looks like the logic is not triggered anyway, since keys are not present in test env.

We would need to add a spec to cover RecaptchaVerifier itself, mocking the variables.

2021-03-23 17:53 UTC, Alexey1100 commented on .env.required
> +RECAPTCHA_SITE_KEY=none
This list contains keys which are required for every environment (see `config/initializers/env_verifier.rb`), and since recaptha is not required, we should remove it from here.

We have `app.json` as a reference list of all env variables, that should be enough :)

2021-03-23 17:58 UTC, kolishchak commented on .env.required
> +RECAPTCHA_SITE_KEY=none
Gotcha
Thanks :)

2021-03-23 18:06 UTC, Alexey1100 requested changes

2021-03-23 18:06 UTC, Alexey1100 commented on config/initializers/recaptcha.rb
> +  config.site_key = ENV['RECAPTCHA_SITE_KEY']
Will the initialiser raise if the keys are empty?

2021-03-23 18:06 UTC, Alexey1100 commented on spec/interactors/accounts/register_spec.rb
> +  describe '#call' do
We need to cover whitelabel registration here as well, otherwise simplecov will mark the branch as uncovered, once we set it up :)

2021-03-24 15:28 UTC, kolishchak commented on app/controllers/accounts_controller.rb
> +    register_account_result = Accounts::Register.call(whitelabel_mission: @whitelabel_mission,
@Alexey1100 we don't create an account, we only initialize it.

In my opinion it's better to provide the account with his filled data and display the error of reCaptcha verification.

2021-03-24 15:29 UTC, kolishchak commented on spec/interactors/accounts/register_spec.rb
> +  describe '#call' do
Done. Thanks for the tip :)

2021-03-24 15:37 UTC, kolishchak commented on config/initializers/recaptcha.rb
> +  config.site_key = ENV['RECAPTCHA_SITE_KEY']
No

2021-03-24 15:43 UTC, Alexey1100 commented on app/controllers/accounts_controller.rb
> +    register_account_result = Accounts::Register.call(whitelabel_mission: @whitelabel_mission,
@kolishchak 

https://github.com/CoMakery/comakery-server/blob/1630c21c9230fe7dafab5747f4421e7a8ca8af2f/app/interactors/accounts/register.rb#L22

2021-03-24 15:47 UTC, Alexey1100 commented on app/controllers/accounts_controller.rb
> +    register_account_result = Accounts::Register.call(whitelabel_mission: @whitelabel_mission,
Yep, I think it makes sense to initialise the instance, but currently the interactor tries to save the record.

2021-03-25 07:00 UTC, Riddlerrr requested changes
Code looks good to me 👍

But when I trying to sign in locally I always getting "Invalid email or password" error
Tried to sing in on `acceptance` branch with the same credentials and it works well.
So it seems something not work properly.
If I understood correctly it's not required any new ENV for the development environment it should just skip recaptcha check, right?

2021-03-25 07:03 UTC, Riddlerrr commented
@kolishchak Could you attach a screenshot with the Recaptcha placed on a page?

2021-03-25 09:05 UTC, zhinfuhnya commented
@Riddlerrr you're right, without the keys it gives out `false` result.

I updated the reCaptcha config as follows:
https://github.com/CoMakery/comakery-server/pull/1950/files#diff-4c1c0812f6507ae00bdd0349a238b9ab95fc9240c4ce2518e5830c45431b0cdaR4

2021-03-26 12:07 UTC, Riddlerrr commented
@zhinfuhnya Now I can sign in with no Recaptcha ENVs locally but can't with configured ones. Not sure is it ok for dev env?
Probably something not configured on Recaptcha side.
Could you check it works on your side?

<img width="1526" alt="CoMakery - Achieve Big Missions 2021-03-26 15-01-28" src="https://user-images.githubusercontent.com/517356/112628830-7c581600-8e44-11eb-843c-06a4a66a22c8.png">

2021-03-26 20:25 UTC, zhinfuhnya commented
@Riddlerrr on my host once again

![image](https://user-images.githubusercontent.com/81186018/112688771-fbb80a80-8e81-11eb-8465-6a6c5cca498e.png)

![image](https://user-images.githubusercontent.com/81186018/112688790-02df1880-8e82-11eb-95f4-23713cefe959.png)

P.S.: you have to register the credentials under the host, that's probably why it didn't work for you : )

2021-03-29 15:57 UTC, Riddlerrr commented
@zhinfuhnya Yeah, I thought about it too. Ok, I think we can merge and test it on demo.

I don't have comments about the code. The only comment about how it looks:
![image](https://user-images.githubusercontent.com/517356/112864215-4aeb7e80-90c0-11eb-8bf0-456168811f68.png)

@aquabu I think we should do something with this ☝️

2021-03-29 15:57 UTC, Riddlerrr approved these changes

2021-03-29 18:28 UTC, kolishchak commented
@Riddlerrr the captcha is placed at the bottom right as required (although I agree that it looks terrible 🙃).

In general I don't see the point of displaying it.

@aquabu what do you think about it?
https://github.com/CoMakery/comakery-server/pull/1950#issuecomment-809498150

P.S.: reference to the ticket description ⬇️ 
https://github.com/CoMakery/comakery-server/issues/1941

2021-03-29 18:37 UTC, aquabu commented
@kolishchak if we don't have to display it, let's not display it :)

2021-03-29 19:59 UTC, kolishchak commented
@aquabu last minor style changes:
https://github.com/CoMakery/comakery-server/pull/1950/commits/b9019a57db0022df25290a3c0a0a9ac756a8c41c

All is done 🚀

2021-03-30 01:35 UTC, Alexey1100 approved these changes

2021-03-30 02:06 UTC, merged