[WIP] Recovery token lifetime
CoMakery/comakery-server pull request #1956
Opened 2021-03-24 19:37 UTC by kolishchak

2021-03-24 22:17 UTC, Alexey1100 approved these changes
👍

I'm leaning towards adding the validation directly to `ApiOreIdWalletRecovery` instead of putting it in more generic `ApiRequestLog`, but it's definitely not blocking :)

2021-03-25 04:53 UTC, aquabu commented on app/models/api_request_log.rb
> +    DateTime.current > created_at + 5.minutes
I think the 5.minutes should be refactored out into a named constant like `ApiRequestLog::TOKEN_EXPIRATION_SECONDS=5.minutes`

2021-03-25 04:58 UTC, aquabu requested changes
Minor refactor suggested.

2021-03-26 03:44 UTC, aquabu approved these changes

2021-03-26 03:44 UTC, aquabu commented
thanks for the refactor @kolishchak 👍

2021-03-26 03:44 UTC, merged