Transfer cancel link should not appear when the transfer is pending
CoMakery/comakery-server pull request #1963
Opened 2021-03-26 11:50 UTC by shoaibmalik786

2021-03-26 18:42 UTC, aquabu requested changes
Please add rspec test coverage for each conditional branch.

2021-03-31 12:35 UTC, shoaibmalik786 commented
@aquabu I have written the rspec. Please have a look.

2021-03-31 23:29 UTC, aquabu commented on app/policies/award_policy.rb
> +  def status_for_cancel?
The case statement is a convoluted which will make it difficult to maintain. There are also unnecessary code branches that could cause unexpected behavior.

I would recommend refactoring `status_for_cancel?` into a `BlockchainTransactable#cancelable?` method which has object access to `status` and `waiting_in_created?`

That method should have a unit test that covers each branch in the conditional statement.



The

2021-03-31 23:30 UTC, aquabu requested changes
Thanks for the additional test. Please refactor the `status_for_cancel?` method.

2021-04-01 09:26 UTC, shoaibmalik786 commented on app/policies/award_policy.rb
> +  def status_for_cancel?
I have made the changes.

2021-04-02 07:43 UTC, aquabu approved these changes

2021-04-02 07:45 UTC, aquabu commented on app/models/concerns/blockchain_transactable.rb
> +      flag = case latest_blockchain_transaction&.status
@shoaibmalik786 thanks for the refactor. Last minor detail. The case statement can just return directly from `cancelable?`. The `flag = ` and `flag` at the end of the method aren't needed. Thanks!

2021-04-02 10:52 UTC, shoaibmalik786 commented on app/models/concerns/blockchain_transactable.rb
> +      flag = case latest_blockchain_transaction&.status
I have removed flag.

2021-04-02 16:24 UTC, aquabu commented on app/models/concerns/blockchain_transactable.rb
> +      flag = case latest_blockchain_transaction&.status
Awesome. Thanks!

2021-04-02 16:25 UTC, merged

2021-04-02 16:27 UTC, Alexey1100 requested changes

2021-04-02 16:27 UTC, Alexey1100 commented on app/models/concerns/blockchain_transactable.rb
> +      case latest_blockchain_transaction&.status
Seems like this doesn't cover all the statuses properly.

Transactable should be cancelable **only** if the latest transaction is created, cancelled or failed, or there are no transactions at all.

2021-04-02 16:44 UTC, aquabu commented on app/models/concerns/blockchain_transactable.rb
> +      case latest_blockchain_transaction&.status
@Alexey1100 hmm... ok. Let's spec that out in pivotal tracker.