API password reset url returns 500 for non ore id wallets
CoMakery/comakery-server pull request #1971
Opened 2021-03-29 19:16 UTC by zhinfuhnya

2021-03-30 01:27 UTC, Alexey1100 requested changes
👍

Pls resolve conflicts with acceptance.
Latest changes removed OreIdAccoynt sync call from the wallet controller.

2021-03-30 11:00 UTC, Riddlerrr approved these changes

2021-03-30 21:00 UTC, Alexey1100 approved these changes

2021-03-31 03:32 UTC, aquabu approved these changes

2021-03-31 03:32 UTC, merged