Remove repeated code from RequiresRecoverySignature
CoMakery/comakery-server pull request #1975
Opened 2021-03-30 08:56 UTC by Riddlerrr

Post refactoring after https://github.com/CoMakery/comakery-server/pull/1969

2021-03-30 21:04 UTC, Alexey1100 requested changes

2021-03-31 07:17 UTC, Riddlerrr commented on app/controllers/api/v1/concerns/requires_signature.rb
>        key = "api::v1::nonce_history:#{whitelabel_mission.id}:#{nonce}"
Yeah, good point 👍

2021-04-02 06:25 UTC, aquabu commented
@Riddlerrr could you verify that there are tests for this. It may be a pure refactoring but want to make sure key signing remains the same.

Also @Alexey1100 if you can sanity check as well that would be great.

2021-04-02 16:26 UTC, Riddlerrr commented
@aquabu Yeah it's pure refactoring. Tests were added in https://github.com/CoMakery/comakery-server/pull/1969

2021-04-02 16:29 UTC, Alexey1100 approved these changes

2021-04-03 00:49 UTC, merged