Add ChainJS-compatible transaction encoding to eth tx wrappers
CoMakery/comakery-server pull request #1992
Opened 2021-04-03 06:15 UTC by Alexey1100

Resolves:
https://www.pivotaltracker.com/story/show/177502244
https://www.pivotaltracker.com/story/show/177615677

- Add object conversion to eth and erc20 tx classes
- Use object conversion in blockchain tx classes to populate tx_raw
- Trim comakery security token abi to include only functions used by Comakery
- Sign eth transactions via OREID UI
- Disable return_signed_transaction for create_tx_params

2021-04-03 17:12 UTC, aquabu commented on app/lib/comakery/eth/tx/erc20/mint.rb
> +    'mint'
I think the method_id should be generated using a hash of the function signature instead of hard coded - that would be better for auditing that the expected method is being called.

2021-04-03 17:17 UTC, Alexey1100 commented on app/lib/comakery/eth/tx/erc20/mint.rb
> +    'mint'
Definitely.
We still need to define function input types to calculate the hash, so the types would be hardcoded, or we can try to extract the id from eth lib, which already parses the abi.

2021-04-03 17:21 UTC, aquabu commented on app/lib/comakery/eth/tx/erc20/security_token/pause.rb
> +    '8456cb59'
Same comment. I think we should show the inputs used to generate the method_id hash. We are defining the arguments and function name defined here. We should provide a function signature string like `baz(uint32,bool)` that it's generated from.

Here's a link to the argument encoding docs for convenience: https://docs.soliditylang.org/en/v0.8.3/abi-spec.html?highlight=argument%20encoding#function-selector-and-argument-encoding

2021-04-03 17:23 UTC, aquabu commented on app/lib/comakery/eth/tx/erc20/security_token/pause.rb
> +  def method_name
maybe we should derive the `method_name` from the signature string... e.g. `baz(uint32,bool)` return s the `method_name` `baz`

2021-04-03 17:26 UTC, aquabu requested changes
check the method_id comments

2021-04-04 18:39 UTC, aquabu commented on app/lib/comakery/eth/tx/erc20.rb
> +    ''
To reduce risk of signing an undefined transaction I think the base class `method_id` and `method_name` should be defined as `raise NotImplementedError`.  

Since this is a template class it's not informative enough to rely on duck typing. It's also not safe to rely on the current default implementation because someone could sign a transaction for the `method_name` or `''`. This might fail, but our faith in that failure relies on some downstream library that we hope would fail for any arbitrary scenario. This could lead to an exploit or simple loss of funds such as batch processing transactions that do nothing with a high gas cost.

### Reasoning for using `NotImplementedError` instead of `NoMethodError`

There is some disagreement on which error should be raised for template interfaces. But I think we should use `raise NotImplementedError`. Here's why...

Technically [the `NotImplementedError` docs](https://ruby-doc.org/core-2.5.0/NotImplementedError.html) say it is for "when a feature is not implemented on the current platform. For example, methods depending on the fsync or fork system calls..."

This might lead us to use `NoMethodError` which [the docs say](https://ruby-doc.org/core-2.5.0/NoMethodError.html) is "Raised when a method is called on a receiver which doesn't have it defined..."

However the interface testing patter in rspec for templates and interfaces typically rely on calling `respond_to?(:method_name)`. This is also the approach advocated by Sandi Metz in [Practical Object Oriented Design in Ruby](https://www.informit.com/store/practical-object-oriented-design-an-agile-primer-using-9780134456478?ranMID=24808).

To use this testing pattern you must use `NotImplementedError` to get the desired `respond_to?` output because:
| Error | `respond_to?(:method_name)` |
| -- | -- |
| NotImplementedError | `false` (what we need for testing the interface) |
| NoMethodError | `true` (won't allow us to test for the implementation) |

Therefore we should use `NotImplementedError` to define the template clearly, avoid the dangers of generic definition, and efficiently test that the templates are fully defined.

2021-04-04 18:43 UTC, aquabu approved these changes
@Alexey1100 I'm merging this and I added a refactoring story to https://www.pivotaltracker.com/n/projects/2167210/stories/177618915

2021-04-04 18:46 UTC, merged

2021-04-05 15:23 UTC, Alexey1100 commented on app/lib/comakery/eth/tx/erc20.rb
> +    ''
Yep I agree, this template class needs some refactoring.

> It's also not safe to rely on the current default implementation because someone could sign a transaction for the method_name or ''.
There's no security risk though, since this template class is never initialised on it's own and the decision of what tx class should be initialised to generate or verify the transaction, placed in the BlockchainTransaction model subclasses logic, where it's hardcoded.