logo URL fix
CoMakery/comakery-server pull request #1998
Opened 2021-04-06 12:51 UTC by olehyev138

2021-04-06 20:13 UTC, Alexey1100 requested changes
@olehyev138 could you pls reference the task on tracker and add a spec.

2021-04-06 21:43 UTC, aquabu commented
@olehyev138 merging. But could you write a spec for this in a follow up PR? I don't want this to break again in the future without us knowing.

2021-04-06 21:43 UTC, aquabu approved these changes

2021-04-06 21:44 UTC, aquabu commented
@olehyev138 looks like @Alexey1100 also requested the spec. Yes, please add that and then we will merge it.

2021-04-06 21:52 UTC, olehyev138 commented
> @olehyev138 looks like @Alexey1100 also requested the spec. Yes, please add that and then we will merge it.

Which spec do you mean? task description from tracker?

2021-04-06 22:25 UTC, aquabu commented
@olehyev138 a spec verifying that `Rails.application.routes.url_helpers.url_for(logo_image)` returns a full path to the image that can be used by clients of the API.

2021-04-08 23:00 UTC, Alexey1100 approved these changes

2021-04-09 02:30 UTC, aquabu approved these changes

2021-04-09 02:30 UTC, merged