API Docs Changes
CoMakery/comakery-server pull request #1999
Opened 2021-04-06 13:13 UTC by shoaibmalik786

2021-04-07 16:23 UTC, Alexey1100 requested changes
@shoaibmalik786 wow that's a lot of work, but I don't think that's what we wanted.
We just wanted to predefine all ids and timestamps of resources used in the spec as described in #1949, not the complete API responses.

That will give us lots of troubles maintaining that : )

2021-04-08 04:06 UTC, shoaibmalik786 commented
> @shoaibmalik786 wow that's a lot of work, but I don't think that's what we wanted.
> We just wanted to predefine all ids and timestamps of resources used in the spec as described in #1949, not the complete API responses.
> 
> That will give us lots of troubles maintaining that : )

There are so many places where we are using random generated hash as token or value and also using random generated emails in request_body, request_query_parameters, response_headers and response_body. What about that?

Should i only change the dynamic value rather than whole request and response parameter's values? Please suggest.

2021-04-08 14:28 UTC, Alexey1100 commented
@shoaibmalik786 yep, all of these random values could be bypassed by passing params on create:

```ruby
create(:account, id: 55, email: 'email55@example.org')
```

Also you could create a set of helpers inside `mom.rb` which will always use only predefined values, and use these helpers for the API specs.

2021-04-08 17:02 UTC, shoaibmalik786 commented
> @shoaibmalik786 yep, all of these random values could be bypassed by passing params on create:
> 
> ```ruby
> create(:account, id: 55, email: 'email55@example.org')
> ```
> 
> Also you could create a set of helpers inside `mom.rb` which will always use only predefined values, and use these helpers for the API specs.

@Alexey1100 Thanks for suggestion but i think we should use these static value in response because it will create the problem if record is already created with id 55 or something else.

2021-04-08 18:10 UTC, Alexey1100 commented
@shoaibmalik786 the database is cleared for every example, so we shouldn't have the conflicts.

2021-04-08 18:13 UTC, Alexey1100 commented
I think the static responses used to render the documentation will defeat the purpose of these specs :)

2021-04-12 07:16 UTC, Riddlerrr commented on app/lib/comakery/api_signature.rb
> -    def sign(private_key)
I'd prefer do not change the main lib code for tests purposes only.
To freeze time you can use `Timecop` gem. https://github.com/travisjeffery/timecop
Like this:
```
  before do
    Timecop.freeze(Time.local(1990))
  end

  after do
    Timecop.return
  end
```
`nonce` also can be stubbed using RSpec:
```
allow_any_instance_of(Comakery::APISignature).to receive(:nonce).and_return('0242d70898bcf3fbb5fa334d1d87804f')
```

2021-04-12 09:21 UTC, shoaibmalik786 commented on app/lib/comakery/api_signature.rb
> -    def sign(private_key)
Ok Thanks

2021-04-21 05:31 UTC, aquabu commented
@shoaibmalik786 @Alexey1100 @Riddlerrr  what's the status on this one? It looks like there are some merge conflicts and failing specs - but other than that how's it going? Would be great to get this one across the finish line. Thanks!

2021-04-21 07:28 UTC, shoaibmalik786 commented
@aquabu I have completed the required changes for this task. some spec are falling here, not able to find the issue because on my machine all specs working fine.

2021-04-21 18:39 UTC, aquabu commented
@shoaibmalik786 there is some CI instability that has been mostly addressed on `acceptance`. I reran the checks here and they passed.

2021-04-21 18:49 UTC, aquabu requested changes
@shoaibmalik786 can you remove the schema.rb changes. There shouldn't be any migrations or changes and it does some odd things like not including indexes and removing tables. If CI is failing try re-running it.

2021-04-21 19:53 UTC, aquabu commented on spec/acceptance/api/v1/11_general_spec.rb
> +        result[0][:response_headers]['ETag'] = 'ETag: W/"65619e25d426a61fdaaea38f54f63b1f"' if status == 200
@shoaibmalik786 we want to avoid the pattern of stubbing every ETag.

Here are a few approaches that might work in order of preference:
* If all the attributes in the response are static (as they should be from the other test changes), the ETag should stay the same and the ETag won't need to be stubbed.
* If the ETag is still changing then the ETag output could be stubbed in the controller, response object or the class generating the etag. This stub could be defined in a test helper that's reusable for all rspec tests that generate api docs. This would keep us from needing to stub the value many times in tests and make the approach easily reusable across tests.
* Finally the Etag could be stripped off the request and only be specified on the authentication pages.

2021-04-22 19:17 UTC, aquabu commented
@shoaibmalik786 thanks for resolving the merge conflicts. 

There are two other items to resolve before merging:
* remove changes to `schema.rb`
* change the way that ETags are stubbed

There are more details on these above.

2021-04-23 04:26 UTC, shoaibmalik786 commented
> @shoaibmalik786 thanks for resolving the merge conflicts.
> 
> There are two other items to resolve before merging:
> 
> * remove changes to `schema.rb`
> * change the way that ETags are stubbed
> 
> There are more details on these above.

I have made the changes. There were some conflicts in schema file which i have resolved. Etag issue also fixed. there are only one spec where i have manually set the Etag value otherwise for all specs Etag value is same every time.

2021-04-28 07:04 UTC, aquabu commented
@shoaibmalik786 if you could, please remove all changes to the schema.rb file so it doesn't appear in the diff. It's hard to tell what's a change vs a reordering and there shouldn't be any schema changes needed. Thanks!

2021-04-30 05:49 UTC, shoaibmalik786 commented
> @shoaibmalik786 if you could, please remove all changes to the schema.rb file so it doesn't appear in the diff. It's hard to tell what's a change vs a reordering and there shouldn't be any schema changes needed. Thanks!

@aquabu I have reverted schema file.

2021-05-05 06:50 UTC, aquabu approved these changes

2021-05-05 07:11 UTC, merged