Recaptcha bugfixes
CoMakery/comakery-server pull request #2037
Opened 2021-04-14 23:15 UTC by Alexey1100

Resolves:
https://www.pivotaltracker.com/story/show/177740456
https://www.pivotaltracker.com/story/show/177704407

- Fix v3 when navigating to page with turbolinks
- Add minimum score for v3
- Fallback to v2 if score is below minimum

Pls note there are two new variables required: `RECAPTCHA_SITE_KEY_V2` and `RECAPTCHA_SECRET_KEY_V2`

2021-04-15 14:58 UTC, zhinfuhnya approved these changes

2021-04-20 17:19 UTC, aquabu approved these changes

2021-04-21 03:47 UTC, aquabu approved these changes

2021-04-21 03:47 UTC, aquabu commented
@Alexey1100 merge conflict.

2021-04-22 01:49 UTC, aquabu requested changes
merge conflicts need to be resolved before merging

2021-04-22 04:00 UTC, aquabu approved these changes

2021-04-22 04:00 UTC, aquabu commented
@Alexey1100 thanks for fixing the merge conflict!

2021-04-22 04:00 UTC, merged