Accounts page
CoMakery/comakery-server pull request #2053
Opened 2021-04-21 19:28 UTC by zhinfuhnya

[#177788836](https://www.pivotaltracker.com/n/projects/2167210/stories/177788836)

2021-04-22 22:54 UTC, Alexey1100 requested changes
Needs a couple of changes and some specs:
- Acceptance spec which actually renders the page under different conditions (Similar to `spec/features/dashboard/accounts/index_spec.rb`)
- Policy spec coverage

2021-04-22 22:54 UTC, Alexey1100 commented on app/models/wallet.rb
> +  after_create_commit { broadcast_append_later_to 'wallets' if account_whitelabel? }
Looks like we need to include whitelabel mission id into turbo stream id.
Otherwise accounts would be leaking across all whitelabel missions.

2021-04-22 22:54 UTC, Alexey1100 commented on app/views/wallets/_wallet.html.erb
> +  <td class="h12 font-weight-medium n10-color"><%= wallet._blockchain %></td>
Should be `wallet.blockchain.name` for the UI.

2021-04-22 22:54 UTC, Alexey1100 commented on app/controllers/accounts_controller.rb
> +    @wallets = Wallet
Should only include wallets from `@whitelabel_mission.managed_accounts`

2021-04-27 23:02 UTC, aquabu approved these changes

2021-04-27 23:46 UTC, Alexey1100 requested changes

2021-04-27 23:46 UTC, Alexey1100 commented on app/controllers/accounts_controller.rb
> +                          .map(&:wallets)
The `.map` will load the complete query result in memory as an array, which might be more than 10k records :)
We need to do wallet load on database side

2021-04-27 23:46 UTC, Alexey1100 commented on app/models/account.rb
> +        broadcast_replace_to 'wl_account_wallets',
We need to include `managed_mission.id` in the web socket channel name `wl_account_wallets`, not in the DOM target.
Otherwise everyone who connected to `wl_account_wallets` channel will see updates for all of the accounts for every white label instance.

2021-04-27 23:46 UTC, Alexey1100 commented on app/models/verification.rb
> +        broadcast_replace_to 'wl_account_wallets',
Same here:

> We need to include managed_mission.id in the web socket channel name wl_account_wallets, not in the DOM target.

2021-04-27 23:46 UTC, Alexey1100 commented on app/models/wallet.rb
> +      broadcast_append_later_to 'wl_account_wallets',
Same here:

> We need to include managed_mission.id in the web socket channel name wl_account_wallets, not in the DOM target.

2021-04-27 23:46 UTC, Alexey1100 commented on app/models/wallet.rb
> +      broadcast_replace_to 'wl_account_wallets',
Same here:

> We need to include managed_mission.id in the web socket channel name wl_account_wallets, not in the DOM target.

2021-04-28 06:57 UTC, aquabu commented
@Alexey1100 can you check if your issue is resolved on this PR?

2021-04-28 21:33 UTC, Alexey1100 approved these changes

2021-04-29 03:44 UTC, merged