Admin access management
CoMakery/comakery-server pull request #2057
Opened 2021-04-22 19:37 UTC by zhinfuhnya

2021-05-03 08:40 UTC, Riddlerrr requested changes
Small visual bug. It shows as current "accounts" and "my projects" in the same time:
<img width="1519" alt="CoMakery - Achieve Big Missions 2021-05-03 11-03-39" src="https://user-images.githubusercontent.com/517356/116853895-71d92b00-abff-11eb-9abb-22f3b2377b40.png">

On the account's page it shows useless pencil. When I click it nothing happens:
<img width="1318" alt="CoMakery - Achieve Big Missions 2021-05-03 11-20-31" src="https://user-images.githubusercontent.com/517356/116855338-e4e3a100-ac01-11eb-935e-ff196c6b7ba5.png">

This button also doesn't work:
<img width="1026" alt="CoMakery Project 2021-05-03 11-26-38" src="https://user-images.githubusercontent.com/517356/116855717-82d76b80-ac02-11eb-9b7f-58c56ec49810.png">

Also, something happened with the header (comakery logo) and the footer:
<img width="509" alt="CoMakery - Achieve Big Missions 2021-05-03 11-29-21" src="https://user-images.githubusercontent.com/517356/116856662-32f9a400-ac04-11eb-9caf-368e8e430951.png">

Overall the code looks really well, great job 👍

2021-05-03 08:40 UTC, Riddlerrr commented on app/controllers/dashboard/accounts_controller.rb
> +           .where(project_roles: { project: @project.object })
What the `@project.object` is mean? I can't found that method.

2021-05-03 08:58 UTC, aquabu commented
I think the two account links correspond to the organizational Accounts and the Project Accounts.

2021-05-03 09:27 UTC, zhinfuhnya commented on app/controllers/dashboard/accounts_controller.rb
> +           .where(project_roles: { project: @project.object })
fetch project record from decorator
https://github.com/CoMakery/comakery-server/blob/acceptance/app/controllers/application_controller.rb#L142

2021-05-03 09:38 UTC, Riddlerrr commented on app/controllers/dashboard/accounts_controller.rb
> +           .where(project_roles: { project: @project.object })
oh, ok, it's decorator

2021-05-03 10:01 UTC, zhinfuhnya commented on app/controllers/dashboard/accounts_controller.rb
> +           .where(project_roles: { project: @project.object })
regarding to pencil on accounts page: our changes do not affect this functionality, most likely requires a separate story.

2021-05-03 10:03 UTC, zhinfuhnya commented on app/controllers/dashboard/accounts_controller.rb
> +           .where(project_roles: { project: @project.object })
I would like to clarify: are you trying to unfollow from the project as an admin? (because there is a validation for unfollow, in which there is a restriction on the destroy of interests for admins)

2021-05-03 10:38 UTC, Riddlerrr commented on app/controllers/dashboard/accounts_controller.rb
> +           .where(project_roles: { project: @project.object })
@zhinfuhnya Please ignore the "unfollow" button issue. It works the same as on acceptance branch, so it's not related this changed and should be fixed seeparately.

2021-05-03 10:40 UTC, Riddlerrr commented on app/controllers/dashboard/accounts_controller.rb
> +           .where(project_roles: { project: @project.object })
I've removed this screenshot from my initial comment to not confuse anyone.

2021-05-03 12:25 UTC, Riddlerrr approved these changes

2021-05-03 17:27 UTC, aquabu requested changes
@zhinfuhnya please fix the accounts edit issue on the accounts page for the CoMakery Security Token token types.

2021-05-04 08:56 UTC, Alexey1100 commented on app/assets/stylesheets/upside.scss
> +//.icon {
Looks like it should be removed

2021-05-04 09:34 UTC, Alexey1100 requested changes
Good job :)

I think there are couple improvements needed:

2021-05-04 09:34 UTC, Alexey1100 commented on app/controllers/projects/invites_controller.rb
> +      @project = Project.find(params[:project_id])
`@project_scope.find` see comment above.

2021-05-04 09:34 UTC, Alexey1100 commented on app/interactors/send_invite.rb
> +      Account.find_by(email: context.params[:email])
Emails are not unique across accounts table, so we should also supply whitelabel mission.
Pls see existing implementation of Admins page.

2021-05-04 09:34 UTC, Alexey1100 commented on app/javascript/controllers/permissions/form_controller.js
> +          this._addFlashMessage('error', 'You are not authorized to perform this action')
I'm thinking about how we can have backend as a single source of truth for all error messages 🤔
Maybe backend can render a turbo frame which will trigger a custom stimulus controller to publish the message.

What do you think?

2021-05-04 09:34 UTC, Alexey1100 commented on app/models/project_role.rb
> +  validates :project_id, uniqueness: { scope: %i[account_id], message: 'already has a role in project' }
We need to add the index here.
See wallets table for an example of scoped unique index.

2021-05-04 09:34 UTC, Alexey1100 commented on spec/controllers/projects/invites_controller_spec.rb
> +  let!(:admin) { create(:account, comakery_admin: true) }
Just to avoid confusion :) `comakery_admin` is not related to projects.
It's a flag to access Missions admin and Tokens admin.

2021-05-04 09:34 UTC, Alexey1100 commented on spec/models/project_role_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
Some shoulda matchers covering validations, enum and associations would be nice here.

2021-05-06 16:17 UTC, Alexey1100 commented on app/javascript/controllers/accept_turbo_stream_controller.js
> +      headers.Accept = ['text/vnd.turbo-stream.html', headers.Accept].join(', ')
Interesting..
Why it doesn't happen by default.

2021-05-06 16:21 UTC, Alexey1100 requested changes
Pls fix schema.rb

2021-05-06 16:21 UTC, Alexey1100 commented on db/schema.rb
> -  create_table "data_migrations", primary_key: "version", id: :string, force: :cascade do |t|
Hmm, this is not the first time we are seeing such weird schema updates.
Wondering what's the reason for that.

2021-05-11 17:02 UTC, aquabu approved these changes

2021-05-11 19:52 UTC, Alexey1100 commented on app/models/project_role.rb
> +                          target: "project_#{project.id}_accounts",
I think there's a little issue which I don't know yet how to handle.
It will append the records to the target table regardless current filtering/sorting/pagination.

So if you are on a page it will append the new records to the end of the page (wrongly), but if you refresh the page records will be gone, depending on what filter/sorting/page you have. 

Maybe we need to disable that until we figure the pattern we need to use in such cases.

2021-05-11 19:55 UTC, Alexey1100 commented on app/models/project.rb
> +  has_many :project_roles # rubocop:todo Rails/HasManyOrHasOneDependent
Non blocking.
We need `dependent: nullify` here.

2021-05-11 20:20 UTC, zhinfuhnya commented on app/models/project_role.rb
> +                          target: "project_#{project.id}_accounts",
Thanks for the note! :)

This issue will be solved if we use `broadcast_append_later_to` (the record will be attached at the end of the table when we switch to the next page)

2021-05-11 20:20 UTC, Alexey1100 approved these changes

2021-05-11 20:24 UTC, Alexey1100 commented on app/models/project_role.rb
> +                          target: "project_#{project.id}_accounts",
Hmm I think the difference between `broadcast_append_to` and `broadcast_append_later_to` is that the second schedules a job for the broadcast while the first one does it inline.
So the result will be the same from user perspective.

2021-05-11 20:26 UTC, Alexey1100 commented
@zhinfuhnya good
pls make sure to update `Api::V1::AccountsController#create` as well, since we have some logic around interests there as well.

2021-05-11 20:34 UTC, Alexey1100 commented on app/models/project_role.rb
> +                          target: "project_#{project.id}_accounts",
Maybe we can update frame id based on current filter/page, so the logic will be only triggered on a first page with default sorting and without filters.

Otherwise it will be super complex to handle :)

2021-05-11 20:39 UTC, zhinfuhnya commented
@Alexey1100 @aquabu I think it would be better to wait for the PR with migrations of interests before merging this branch into the acceptance.

2021-05-11 21:50 UTC, merged