updated transfer columns
CoMakery/comakery-server pull request #2059
Opened 2021-04-22 21:08 UTC by olehyev138

Update project transfer page table columns

See attached image for how it will look. It's not pixel perfect but is pretty close to how it will look.

Acceptance:

- Rename "Transfer Name" to "Transfer"

- Rename "Account" column to "To"

- Include the blockchain address of the recipient in the "To" column. This is the users primary wallet address for the project token's blockchain network

- Rename "Transferred By" to "From". The address is a link to the blockchain explorer.

- Only display the "Total Amount" of the transfer - not quantity or amount

- Move the verification to it's own column

- Status no longer includes the transaction "tx" link

- All status wallet payment and cancelation steps still work correctly

- History column includes the "tx" transaction link

- Transferred remains

- Remove created date

2021-04-26 00:14 UTC, aquabu requested changes

2021-04-26 00:14 UTC, aquabu commented on app/views/dashboard/transfers/_transfer.html.erb
> +      <% sender_wallet_address = nil %>
This is too much logic for the view. I recommend moving the logic to the decorator classes, unit testing the decorator classes and avoiding setting any variables in the view.

2021-04-26 00:14 UTC, aquabu commented on app/views/dashboard/transfers/_transfer.html.erb
> +    <% if @project.token %>
Just noticing that this code has too much logic for the view - much of which was already there. The view should make simpler checks and should avoid this amount of nested logic too avoid bugs.

I recommend moving the logic to decorators and adding additional unit testing it there.

2021-04-26 19:54 UTC, aquabu requested changes

2021-04-26 19:54 UTC, aquabu commented on app/views/dashboard/transfers/_transfer.html.erb
> +      <% sender_wallet_address = nil %>
should not set variables in the view

2021-04-26 19:54 UTC, aquabu commented on app/views/dashboard/transfers/_transfer.html.erb
> +        <% sender_wallet_address = transfer.blockchain_transactions.succeed.last&.source %>
move this `sender_wallet_address` logic to `transfer.sender_wallet_address` transfer decorator function with a unit test

2021-04-26 19:54 UTC, aquabu commented on app/views/dashboard/transfers/_transfer.html.erb
> +        <% sender_wallet_url = sender_wallet_address && transfer.token ? transfer.token.blockchain.url_for_address_human(sender_wallet_address) : nil %>
move this `sender_wallet_url` logic to `transfer.sender_wallet_url` transfer decorator function with a unit test

2021-04-26 19:54 UTC, aquabu commented on app/views/dashboard/transfers/_transfer.html.erb
> +      <%= render partial: "account", locals: {account: transfer.account, wallet: sender_wallet_address, wallet_url: sender_wallet_url} %>
use the `transfer` decorator methods for `transfer.sender_wallet_address` and `transfer.sender_wallet_url`

2021-04-26 19:54 UTC, aquabu commented on app/views/dashboard/transfers/_transfer.html.erb
> +      <% sender_wallet_address = nil %>
confirm that there is an feature spec that tests this larger if statement

2021-04-26 19:54 UTC, aquabu commented on app/views/dashboard/transfers/_transfer.html.erb
> +    <% if current_account&.decorate&.can_send_awards?(transfer.project) %>
`current_account&.decorate` can happen in the controller 
`can_send_awards?` should be a AwardPolicy check, also confirm it is unit tested.

2021-04-26 19:54 UTC, aquabu commented on app/views/dashboard/transfers/_transfer.html.erb
> +      <% if transfer.token&.blockchain&.supported_by_ore_id? && current_account&.ore_id_account.nil? %>
this can be moved to a `transfer` decorator method `transfer.payable_by_ore_id?(current_account)` and unit tested

2021-04-26 19:54 UTC, aquabu commented on app/views/dashboard/transfers/_transfer.html.erb
> +    <% if current_account&.decorate&.can_send_awards?(transfer.project) %>
In addition to unit testing make sure each of these conditions is testing in an feature integration test

2021-04-26 19:54 UTC, aquabu commented on app/views/dashboard/transfers/_transfer.html.erb
> +      <% if transfer.recipient_address.blank? && current_account == transfer.account %>
This logic looks overly complex and could be a source of bugs. Simplify this by removing this `set wallet` if branch and render `shared/transfer_button_public` which will display "needs wallet" if it needs one.

2021-04-26 19:54 UTC, aquabu commented on app/views/dashboard/transfers/_transfer.html.erb
> +      <% if transfer.blockchain_transactions.size > 0 %>
refactor `transfer.blockchain_transactions.size > 0` to the transfer decorator as `transfer.has_blockchain_transactions?` and unit test it.

2021-04-26 21:17 UTC, olehyev138 commented on app/views/dashboard/transfers/_transfer.html.erb
> +      <% if transfer.recipient_address.blank? && current_account == transfer.account %>
so just remove the whole if-else statement and just put in transfer_button_public render?

2021-04-27 22:47 UTC, olehyev138 commented
to solve some Test failed, need @Alexey1100's help

2021-05-07 22:02 UTC, aquabu commented on app/views/dashboard/transfers/_transfer.html.erb
> +      <% if transfer.recipient_address.blank? && current_account == transfer.account %>
yes I think so. @Alexey1100 does that sound correct?

2021-05-07 22:26 UTC, Alexey1100 commented on app/views/dashboard/transfers/_transfer.html.erb
> +      <% if transfer.recipient_address.blank? && current_account == transfer.account %>
It's a bit tricky yes, since `shared/transfer_button_public` is rendered for broadcast and doesn't know about current user and it's wallet. That's why the set wallet was extracted from there.

@aquabu You are right, the `needs wallet` message still will be displayed, but we will not be able to link contributor to wallets page as currently.

2021-05-07 23:09 UTC, aquabu commented on app/views/dashboard/transfers/_transfer.html.erb
> +      <% if transfer.recipient_address.blank? && current_account == transfer.account %>
ok - I think we can resolve in a future PR.

2021-05-11 17:21 UTC, closed without merging