remove whitelabel-projects-task
CoMakery/comakery-server pull request #2064
Opened 2021-04-23 23:19 UTC by olehyev138

When the WHITELABEL environment variable is set to true then the project "Tasks" menu item should not appear

2021-04-26 00:01 UTC, aquabu requested changes
@olehyev138 
* please add an rspec integration test for when the menu item appears and when it does not appear
* also the URL should not be accessible, this should also have a test

2021-04-28 06:58 UTC, aquabu commented
@olehyev138 this still needs the rspec tests mentioned above. Thanks.

2021-04-29 19:23 UTC, aquabu approved these changes

2021-04-29 19:23 UTC, merged

2021-04-30 03:52 UTC, Alexey1100 commented on app/controllers/projects_controller.rb
> +        whitelabel: ENV['WHITELABEL'] || false,
We should check `@whitelabel_mission` variable here which indicates that request comes from whitelabel.

`ENV['WHITELABEL']` is only used for a specific case setup when the complete deployment is whitelabel.

2021-04-30 03:53 UTC, Alexey1100 commented on app/policies/project_policy.rb
> +    return false if ENV['WHITELABEL'] == true
Same here, we need to pass @whitelabel_mission into policy.

2021-04-30 03:55 UTC, Alexey1100 commented on spec/features/tasks/project_tasks.spec.rb
> +    login(ready_task.account)
Hmm I think these specs might not be working correctly...
Since we are not switching env to whitelabel between examples.