Migrate interests to project roles
CoMakery/comakery-server pull request #2095
Opened 2021-05-11 10:03 UTC by zhinfuhnya

2021-05-13 17:28 UTC, o-bahriy commented on app/models/project.rb
> +    project.add_account(new_owner)
here it should be add_admin

2021-05-13 23:37 UTC, aquabu requested changes

2021-05-13 23:37 UTC, aquabu commented on db/data_migrations/20210512175535_update_project_roles_counter.rb
> +  def up
The failure rate for data migrations is pretty high because there's often unexpected data values or nils. Please download the demo server data and run the data migrations. The also write specs to verify it works for the expected case and any failures you find with the demo data. Thanks!

2021-05-13 23:37 UTC, aquabu commented on app/controllers/accounts_controller.rb
> +        auto_interest_project.add_account(@account)
If there isn't a spec it would good to write one verifying that it's not possible to get added more than once. Historically there have been some bugs around displaying the same account more than once on the accounts page.

2021-05-14 10:20 UTC, zhinfuhnya commented on db/data_migrations/20210512175535_update_project_roles_counter.rb
> +  def up
Migration was run on actual data 👌 

Also added spec https://github.com/CoMakery/comakery-server/pull/2095/commits/2bf0b09dbb4a86d1f9f21fb881f684a0fc031ffa

2021-05-14 10:20 UTC, zhinfuhnya commented on app/controllers/accounts_controller.rb
> +        auto_interest_project.add_account(@account)
We already have specifications that say we cannot add more than one account.

2021-05-14 16:46 UTC, aquabu approved these changes

2021-05-18 10:42 UTC, o-bahriy approved these changes

2021-05-19 10:03 UTC, zhinfuhnya commented
Includes the following PR's:
https://github.com/CoMakery/comakery-server/pull/2097
https://github.com/CoMakery/comakery-server/pull/2120

2021-05-21 14:34 UTC, Alexey1100 requested changes

2021-05-21 14:34 UTC, Alexey1100 commented on app/controllers/projects_controller.rb
> +  def awards
This page was deleted recently, so it shouldn't be here.

2021-05-21 14:34 UTC, Alexey1100 commented on spec/controllers/dashboard/accesses_controller_spec.rb
> -    context 'with whitelabel mission' do
Hmm do we still have that coverage somewhere else?
I can't find it :)

Looks like the interaction is moved into SendInvite class but it's specs don't cover whitelabel interactions.

2021-05-24 23:41 UTC, Alexey1100 approved these changes

2021-05-24 23:43 UTC, aquabu approved these changes

2021-05-24 23:43 UTC, merged