Update/transfer table columns
CoMakery/comakery-server pull request #2107
Opened 2021-05-13 02:15 UTC by olehyev138

Update Transfer table columns

2021-05-18 09:00 UTC, zhinfuhnya requested changes

2021-05-18 17:29 UTC, olehyev138 commented on app/models/concerns/blockchain_transactable.rb
> +      set_counter_cache
It's so that `set_counters `can be used as a standalone method as well to populate the size without the callback method, and since this is a callback method, an added argument is must in `:after_add` and `:after_remove` callbacks

2021-05-18 17:29 UTC, olehyev138 commented on db/migrate/20210517195832_initialize_blockchain_transactions_count.rb
> +    Award.find_each { |award| award.set_counter_cache }
Ah I see, I will make the specs.

2021-05-18 17:38 UTC, olehyev138 commented on app/decorators/award_decorator.rb
> +    if paid?
I'll remove this

2021-05-18 17:38 UTC, olehyev138 commented on app/views/dashboard/transfers/_transfer.html.erb
> +        <%= link_to "#{transfer.blockchain_transactions_count} Tx ➔", project_dashboard_transfer_path(transfer.project, transfer), class: 'transfers-table__transfer__button__history' %>
Could you explain what you mean?

2021-05-18 19:25 UTC, olehyev138 commented on app/views/dashboard/transfers/_transfer.html.erb
> +        <%= link_to "#{transfer.blockchain_transactions_count} Tx ➔", project_dashboard_transfer_path(transfer.project, transfer), class: 'transfers-table__transfer__button__history' %>
fixed it

2021-05-20 01:21 UTC, Alexey1100 requested changes
Transfer transactions link is missing.

This branch:
<img width="1168" alt="Screenshot 2021-05-20 at 05 19 56" src="https://user-images.githubusercontent.com/10757562/118904600-42c6f700-b92b-11eb-8d25-887f1631b83e.png">

Acceptance:
<img width="1159" alt="Screenshot 2021-05-20 at 05 20 09" src="https://user-images.githubusercontent.com/10757562/118904584-3773cb80-b92b-11eb-92f9-c37bedf7e99a.png">

2021-05-20 01:21 UTC, Alexey1100 commented on db/schema.rb
> +  enable_extension "pg_stat_statements"
Pls revert the extension.

2021-05-20 01:21 UTC, Alexey1100 commented on spec/features/dashboard/transfers/index_page_spec.rb
> -      expect(page).to have_selector "a[href='#{project_dashboard_transfer_path(@award.project, @award)}']"
This link should be present

2021-05-26 17:29 UTC, aquabu commented
This PR is merged or related code is resolved by https://github.com/CoMakery/comakery-server/pull/2138

2021-05-26 17:29 UTC, closed without merging