Update project role policy
CoMakery/comakery-server pull request #2113
Opened 2021-05-14 18:06 UTC by zhinfuhnya

2021-05-17 20:47 UTC, aquabu requested changes

2021-05-17 20:47 UTC, aquabu commented on app/policies/project_role_policy.rb
> +    when :admin
Something about this looks odd. If you are `:admin` and `project_admin?` but not `project_owner?` should you be able to update? 

Maybe I'm missing something but it seems that with this logic an `:admin` with `project_admin?` would not be able to update but `:interested` `project_admin?` would.

2021-05-18 09:40 UTC, zhinfuhnya commented on app/policies/project_role_policy.rb
> +    when :admin
Accounts with the role of admin can only edit the superior (project owner). That is, admins can not change each other's role (which makes sense to me).

Only owners and admins can update roles of interested and observers. 

Do you agree with me?

2021-05-18 09:42 UTC, zhinfuhnya commented on app/policies/project_role_policy.rb
> +    when :admin
> If you are :admin and project_admin? but not project_owner? should you be able to update?

it is impossible because the condition to check the editing of their role is met, admins can't edit themselves.

2021-05-18 13:31 UTC, Alexey1100 commented on app/policies/project_role_policy.rb
> +    when :admin
@zhinfuhnya yes, you're right.

I think the confusion here is because the method is a bit hard to read.
Maybe instead of the case condition we should add a bunch of helpers with clear naming.
E.g:

`can_edit_admin_role?`
`can_edit_interested_role?`
`can_edit_observer_role?`
`can_edit_own_role?`

2021-05-18 14:29 UTC, zhinfuhnya commented on app/policies/project_role_policy.rb
> +    when :admin
@Alexey1100 agree with you.
Added review fixes.

2021-05-18 21:59 UTC, aquabu approved these changes

2021-05-18 21:59 UTC, merged