Visibility restrictions by project roles
CoMakery/comakery-server pull request #2120
Opened 2021-05-17 18:35 UTC by zhinfuhnya

2021-05-18 22:23 UTC, aquabu requested changes

2021-05-18 22:23 UTC, aquabu commented on app/policies/project_policy.rb
> +    show_contributions? || project_observer? || project_interested?
users who are only `interested` shouldn't be able to see the accounts. They would only be able to see the accounts if `show_contributions?` is true.

2021-05-18 22:23 UTC, aquabu commented on app/policies/project_policy.rb
> +    show_contributions? || project_observer? || project_interested?
same as for `#accounts?`

you can delete `project_interested?` here. Interested can only see transfers when `show_contributions?` is true.

2021-05-18 22:23 UTC, aquabu commented on app/views/dashboard/accounts/_account.html.erb
> +              <svg class="n9-color" width="18" height="4" viewBox="0 0 18 4" fill="none" xmlns="http://www.w3.org/2000/svg">
Maybe move this svg to its own file or partial?

2021-05-19 07:57 UTC, zhinfuhnya commented on app/views/dashboard/accounts/_account.html.erb
> +              <svg class="n9-color" width="18" height="4" viewBox="0 0 18 4" fill="none" xmlns="http://www.w3.org/2000/svg">
I think we can leave it as it is, since we do not reuse svg anywhere else.

2021-05-20 16:48 UTC, closed without merging