HW: Check for enough gas to send a tx
CoMakery/comakery-server pull request #2122
Opened 2021-05-18 10:14 UTC by Riddlerrr

Second part of the task: https://www.pivotaltracker.com/story/show/178015066

2021-05-18 12:39 UTC, Alexey1100 approved these changes

2021-05-18 13:08 UTC, zhinfuhnya commented on hotwallet/tests/EthereumBlockchain.isTransactionValid.test.js
> +    txRaw: '{"from":"0x15b4eda54e7aa56e4ca4fe6c19f7bf9d82eca2fc","to":"0xE322488096C36edccE397D179E7b1217353884BB","value":"0x0","contract":{"abi":[{"constant":true,"inputs":[],"name":"name","outputs
Line is too long :)

I think it would be a good to format
https://codeshare.io/2jpOyL

2021-05-18 22:11 UTC, aquabu commented on hotwallet/tests/EthereumBlockchain.isTransactionValid.test.js
> +    txRaw: '{"from":"0x15b4eda54e7aa56e4ca4fe6c19f7bf9d82eca2fc","to":"0xE322488096C36edccE397D179E7b1217353884BB","value":"0x0","contract":{"abi":[{"constant":true,"inputs":[],"name":"name","outputs
yes, also me be better to load this from a test fixture file

2021-05-19 04:44 UTC, aquabu requested changes
test with long string needs a fix

2021-05-19 23:52 UTC, aquabu approved these changes

2021-05-19 23:53 UTC, merged