Optimize token balances
CoMakery/comakery-server pull request #2128
Opened 2021-05-19 14:30 UTC by zhinfuhnya

2021-05-19 16:41 UTC, Riddlerrr approved these changes
👍

2021-05-19 19:42 UTC, Alexey1100 requested changes
Pls check the caching key with pagination, as mentioned on call and regenerate api docs, so pagination headers would be displayed in the docs.

2021-05-21 13:31 UTC, Alexey1100 requested changes

2021-05-21 13:31 UTC, Alexey1100 commented on public/doc/api/v1/ii._accounts/token_balances.html
> +                  <span class="name">page</span>
Hmm where does this update come from?
There's no doc spec changes included in the PR.

2021-05-25 16:28 UTC, Alexey1100 approved these changes

2021-05-25 16:49 UTC, aquabu approved these changes

2021-05-25 16:50 UTC, merged