Header project token details
CoMakery/comakery-server pull request #2130
Opened 2021-05-19 19:27 UTC by zhinfuhnya

2021-05-19 20:00 UTC, Alexey1100 requested changes
Will crash on projects without token.

2021-05-19 20:00 UTC, Alexey1100 commented on app/javascript/components/layouts/ProjectSetupHeader.jsx
> +          <div style={{ display: 'flex' }}>
Should only be displayed if project token is present.

2021-05-20 20:07 UTC, aquabu commented on app/decorators/project_decorator.rb
> +  def header_props # rubocop:todo Metrics/CyclomaticComplexity
Please refactor out some of the conditionals instead of disabling Rubocop. This will help us keep the codebase more maintainable long term.

I think in this case the 5 `token&.` statements may just need to be a single branching conditional on something like `if token.present?`

2021-05-20 20:08 UTC, aquabu requested changes
refactor cyclomatic complexity

2021-05-21 13:27 UTC, Alexey1100 requested changes

2021-05-21 13:27 UTC, Alexey1100 commented on app/decorators/project_decorator.rb
> +          esize_to_fill: [100, 100]
Typo here

2021-05-21 13:27 UTC, Alexey1100 commented on app/decorators/project_decorator.rb
> +        network: token.blockchain_network,
This field is deprecated, should use `token.blockchain.name` instead

2021-05-21 13:28 UTC, Alexey1100 commented on app/decorators/project_decorator.rb
> +          esize_to_fill: [100, 100]
Pls add a spec so this error would be caught.

2021-05-24 17:23 UTC, aquabu approved these changes

2021-05-24 17:24 UTC, Alexey1100 approved these changes

2021-05-24 17:24 UTC, merged