reorganize transfer pages
CoMakery/comakery-server pull request #2131
Opened 2021-05-19 21:36 UTC by olehyev138

Reorganize Transfer page and update styles

2021-05-19 22:25 UTC, Alexey1100 requested changes

2021-05-19 22:25 UTC, Alexey1100 commented on app/controllers/dashboard/transfers_controller.rb
> -  def prioritize
We are using this method, pls put it back : )

2021-05-19 22:33 UTC, olehyev138 commented on app/controllers/dashboard/transfers_controller.rb
> -  def prioritize
done

2021-05-20 01:34 UTC, Alexey1100 requested changes
Incorrect transfer recipient wallet address.

Also looks like this PR has some conflicts with #2107.
Could you merge them in one PR, so it would be easier to review and debug : )

2021-05-20 01:34 UTC, Alexey1100 commented on app/views/dashboard/transfers/_hot_wallet_mode.html.erb
> +                     style: 'border-left: none !important; padding-right: 45px; width: max-content;',
Pls put the styles into css file.

2021-05-20 01:34 UTC, Alexey1100 commented on app/views/dashboard/transfers/_transfer.html.erb
> +      <%= render partial: "account", locals: {account: transfer.account, wallet: sender_wallet_address, wallet_url: sender_wallet_url} %>
Looks like there's a confusion.

`transfer.account` is the recipient not the sender, so we are rendering here the recipient account but with wallet address of the sender.

2021-05-26 17:29 UTC, aquabu commented
This PR is merged or related code is resolved by https://github.com/CoMakery/comakery-server/pull/2138

2021-05-26 17:29 UTC, closed without merging