Update/coverage score
CoMakery/comakery-server pull request #2149
Opened 2021-06-01 01:05 UTC by olehyev138

improve Total coverage score

2021-06-01 18:56 UTC, aquabu commented on app/jobs/ore_id_wallet_opt_in_tx_create_job.rb
> +    wait_time = wallet_provision.next_sync_allowed_after - Time.current
@olehyev138 are there tests for each of the logic branches here? If not tests should be added to get to full coverage.

2021-06-01 19:06 UTC, olehyev138 commented on app/jobs/ore_id_wallet_opt_in_tx_create_job.rb
> +    wait_time = wallet_provision.next_sync_allowed_after - Time.current
@aquabu
it's working well like the previous tests. I only change the `if-else` to `ternary operator`

2021-06-01 23:01 UTC, aquabu requested changes

2021-06-01 23:01 UTC, aquabu commented on app/jobs/ore_id_wallet_opt_in_tx_create_job.rb
> +    wait_time = wallet_provision.next_sync_allowed_after - Time.current
@olehyev138 hmm, seems like it shouldn't be working because: 
* `Time.current.class` returns `ActiveSupport::TimeWithZone`
* `Time.current.positive?` raises `NoMethodError: undefined method `positive?'`
* In this case it is calling `positive` without the question mark which wouldn't even be defined on `Float` or `Integer` if the type was coerced to one of those.

This makes me wonder if there is a test because if there was one it seems like it should be failing. 

Could you either add a test or provide a link to the test. Thanks!

2021-06-02 21:33 UTC, olehyev138 commented on app/jobs/ore_id_wallet_opt_in_tx_create_job.rb
> +    wait_time = wallet_provision.next_sync_allowed_after - Time.current
I'll make new PR for this

2021-06-04 03:08 UTC, aquabu approved these changes

2021-06-04 03:08 UTC, merged