Algo token url
CoMakery/comakery-server pull request #2161
Opened 2021-06-03 10:03 UTC by Riddlerrr

task: https://www.pivotaltracker.com/story/show/178387477

2021-06-03 15:46 UTC, zhinfuhnya approved these changes

2021-06-04 03:05 UTC, aquabu requested changes

2021-06-04 03:05 UTC, aquabu commented on app/decorators/project_decorator.rb
> +        address_url: (token.blockchain.url_for_token_human(token.contract_address) if token.contract_address),
I may be wrong about this, but it might be better to handle this as a method on a Token decorator instead of by modifying all the blockchain template definitions.

Consider that:
* For first layer tokens like Bitcoin, ETH, Algos, etc there won't be a token contract address. This will lead confusion when implementing the template. 
* The information needed to display the token address should already be available on the token model. We use it in a lot of places.

2021-06-04 03:05 UTC, aquabu commented on app/models/blockchain/cardano.rb
> +  def url_for_token_human(addr)
If this does remain in the token template models instread of going in a decorator it seems like this code is repeated a lot and might be better in a base class that is overridden for exceptions.

2021-06-04 06:52 UTC, Riddlerrr commented on app/models/blockchain/bitcoin.rb
> +  def url_for_token_human(addr)
It is explorer site specific thing. We have own explorer site for each blockchain so I think it is correct place to store this urls.
We will not generate this URL for non-contracts tokens:
https://github.com/CoMakery/comakery-server/blob/ba6b77a65a3d9ee5e047f145576f89f1222dceea/app/decorators/token_decorator.rb#L17-L21

2021-06-04 06:53 UTC, Riddlerrr commented on app/decorators/project_decorator.rb
> +        address_url: (token.blockchain.url_for_token_human(token.contract_address) if token.contract_address),
I extracted to token decorator

2021-06-04 07:10 UTC, Riddlerrr commented on app/models/blockchain/cardano.rb
> +  def url_for_token_human(addr)
As I remember we decided to add a new method to each blockchain class and template instead of adding into the main class.
@Alexey1100 Am I correct?

2021-06-04 12:00 UTC, Alexey1100 commented on app/models/blockchain/cardano.rb
> +  def url_for_token_human(addr)
Hmm, true.
I think these irregularities and confusion arise here because it's not a property of Blockchain, it should be defined in TokenType.

We can add something like `TokenType#url_for_self..` which:
1) in case of native coins will return just the homepage of blockchain/coin
2) in case of ERC20 it will call `Blockchain::Ethereum#url_for_address...` via `attrs[:blockchain]` with `attrs[:contract_address]` as a param
3) for Algorand Assets it will call `Blockchain::Algorand#url_for_asset...`
4) for Algorand Apps `Blockchain::Algorand#url_for_app...`

We already have all these helpers implemented and we can add the delegation to token, so it would work like this:
`token.url_for_self_human`

2021-06-04 12:09 UTC, Alexey1100 commented on app/models/blockchain/cardano.rb
> +  def url_for_token_human(addr)
In short:
The url depends both on Blockchain and TokenType, but Blockchain only provides the explorer url and doesn't know anything about token types or contract addresses. TokenType knows on what blockchain it's running and it's own contract address, so the helper should be there.

2021-06-07 09:41 UTC, Riddlerrr commented
I did required changes. Ready to review again.

2021-06-07 16:32 UTC, Alexey1100 commented on app/models/token_type/algorand_security_token.rb
> +    "https://#{blockchain.explorer_human_host}/application/#{contract_address}"
Should use `blockchain.url_for_app_human`.
I think we only have `blockchain.url_for_app_api` since app support for explorer has been added just recently, so we need to add that.

2021-06-07 16:33 UTC, Alexey1100 commented on app/models/token_type/asa.rb
> +    "https://#{blockchain.explorer_human_host}/asset/#{contract_address}"
Should use `blockchain.url_for_asset_human`.

2021-06-07 16:38 UTC, Alexey1100 commented on lib/generators/token_type/templates/token_type_spec.erb
> +    let(:attrs) { { contract_address: nil, blockchain: Blockchain::Blockchain.new } }
Looks like this spec template will be failing by default, since `Blockchain::Blockchain.new` is not defined.

Probably better to mock `Blockchain#explorer_host`

2021-06-07 16:43 UTC, Alexey1100 commented on app/decorators/project_decorator.rb
> +        address: helpers.middle_truncate(token.token_type.human_url_name),
Probably good to add a feature spec, to keep track that the link is present and working.

2021-06-08 19:42 UTC, aquabu approved these changes

2021-06-08 19:42 UTC, merged