ImagePreparer: Specify attribute to apply options
CoMakery/comakery-server pull request #2188
Opened 2021-06-17 08:42 UTC by Riddlerrr

task:  https://www.pivotaltracker.com/story/show/178559683

2021-06-21 19:16 UTC, Alexey1100 requested changes
Oops I've reviewed the https://github.com/CoMakery/comakery-server/pull/2192 first.

Pls see comments there, which mostly relate to code in this PR, or maybe we can merge them in one.

2021-06-22 00:02 UTC, aquabu approved these changes

2021-06-22 00:03 UTC, aquabu requested changes
see comment

2021-06-22 05:58 UTC, Riddlerrr commented on app/controllers/award_types_controller.rb
> +    if @award_type.save_if_no_errors
Explained here https://github.com/CoMakery/comakery-server/pull/2192#discussion_r655891324

2021-06-22 06:10 UTC, Riddlerrr commented
All these changes in https://github.com/CoMakery/comakery-server/pull/2192
Closing this PR to not confuse

2021-06-22 06:10 UTC, closed without merging