Remove image size restrictions
CoMakery/comakery-server pull request #2192
Opened 2021-06-21 10:30 UTC by Riddlerrr

Actual changes for the task: https://www.pivotaltracker.com/story/show/178559683

Should be merged after refactoring PR: https://github.com/CoMakery/comakery-server/pull/2188

2021-06-21 19:12 UTC, Alexey1100 requested changes

2021-06-21 19:12 UTC, Alexey1100 commented on spec/models/mission_spec.rb
> -  it_behaves_like 'active_storage_validator', %w[image logo whitelabel_logo whitelabel_logo_dark whitelabel_favicon]
I think we need to implement ImagePreparer spec as shared example, and then calling it in model spec defining what fields should be processed, similar as we had before with ActiveStorageValidator.

This way we can be sure that the attachments set correctly on model level, having 100% coverage.

2021-06-21 19:12 UTC, Alexey1100 commented on app/models/application_record.rb
> +  def save_if_no_errors
Hmm what's the purpose of this method?

`#save` and `#update` will return false if there are any errors.

2021-06-21 19:12 UTC, Alexey1100 commented on app/models/concerns/prepare_image.rb
> +        def #{name}=(attachable)
Is this part covered with specs?
I think a shared example would be helpful.

2021-06-22 00:04 UTC, aquabu commented on app/models/concerns/prepare_image.rb
> +        def #{name}=(attachable)
+1

2021-06-22 05:41 UTC, Riddlerrr commented on app/models/application_record.rb
> +  def save_if_no_errors
It's a hack.
We can add an error during image processing but if we call regular `#save` it will clear all errors and do validation from scratch. But we want to show that image error instead.

2021-06-22 07:46 UTC, Riddlerrr commented on app/models/project.rb
> +  has_one_attached_and_prepare_image :transfers_csv
mindfulness 👍

2021-06-22 09:31 UTC, Riddlerrr commented on app/models/application_record.rb
> +  def save_if_no_errors
I thought about it more and came up with better approach. Now it close to perfect =)

I save an error in `uploaded_image_errors` variable and set it in `before_validation` callback, so we can use usual `save` and `update` methods

2021-06-22 21:36 UTC, Alexey1100 approved these changes

2021-06-22 21:45 UTC, aquabu approved these changes

2021-06-22 21:45 UTC, merged