Coverage controllers projects
CoMakery/comakery-server pull request #2197
Opened 2021-06-26 21:28 UTC by olehyev138

Improve projects controllers coverage score to 100%

2021-06-28 16:51 UTC, aquabu commented on app/controllers/projects_controller.rb
> -    def project_detail_path
@olehyev138 just checking why this is deleted? Is it no longer used?

2021-06-28 16:54 UTC, aquabu requested changes

2021-06-28 16:54 UTC, aquabu commented on app/controllers/projects_controller.rb
> -    def mission_props(mission)
Is this also no longer used?

2021-06-28 19:57 UTC, olehyev138 commented on app/controllers/projects_controller.rb
> -    def mission_props(mission)
this is not used too

2021-06-28 19:59 UTC, olehyev138 commented on app/controllers/projects_controller.rb
> -    def mission_props(mission)
@aquabu they are not used and so I removed theme instead add tests.

2021-06-29 18:18 UTC, aquabu approved these changes

2021-06-29 22:08 UTC, merged