Creating new user or editing permission of the existing user breaks the Accounts table design
CoMakery/comakery-server pull request #2204
Opened 2021-06-30 11:42 UTC by zhinfuhnya

https://www.pivotaltracker.com/n/projects/2167210/stories/178614552

2021-07-05 16:26 UTC, Riddlerrr approved these changes
👍

2021-07-05 16:31 UTC, Alexey1100 requested changes

2021-07-05 16:31 UTC, Alexey1100 commented on app/controllers/projects/accounts/settings_controller.rb
> +    @project_role = ProjectRole.find_by(project_id: params[:project_id], account_id: params[:account_id])
```suggestion
    @project_role = ProjectRole.find_by!(project_id: params[:project_id], account_id: params[:account_id])
```

Otherwise it may raise 500 on next line.

2021-07-05 16:31 UTC, Alexey1100 commented on app/controllers/projects/accounts/settings_controller.rb
> +  def show
We need to add policy here, otherwise any logged in user can see an account role when following the link, even when not having access to the project.

```ruby
authorize @project, :accounts?
```

2021-07-05 16:36 UTC, Alexey1100 commented on app/controllers/projects/accounts/settings_controller.rb
> +  def show
Ahh okay, we are not displaying role name in the template, only id.
Nevertheless worth adding the policy check.

2021-07-05 18:24 UTC, Alexey1100 requested changes
Still will raise 500 in template if project role is not found :)

2021-07-06 16:30 UTC, Alexey1100 approved these changes

2021-07-07 00:13 UTC, merged