Increase invite token length
CoMakery/comakery-server pull request #2209
Opened 2021-07-01 15:54 UTC by zhinfuhnya

https://www.pivotaltracker.com/n/projects/2167210/stories/178703558

2021-07-02 18:29 UTC, Alexey1100 requested changes

2021-07-02 18:29 UTC, Alexey1100 commented on app/models/invite.rb
>    has_secure_token
I think it should be:

```ruby
has_secure_token :token, length: TOKEN_LENGTH
```

2021-07-02 18:29 UTC, Alexey1100 commented on app/models/invite.rb
> +  def self.generate_unique_secure_token
Looks like we don't need this method.

2021-07-02 18:29 UTC, Alexey1100 commented on spec/models/invite_spec.rb
> +  describe '#pending' do
Pending is a class method :)

2021-07-02 19:35 UTC, zhinfuhnya commented on app/models/invite.rb
>    has_secure_token
according to the documentation it should work but in practice I get an error:
`ArgumentError (wrong number of arguments (given 2, expected 0..1))`

2021-07-02 19:36 UTC, zhinfuhnya commented on app/models/invite.rb
> +  def self.generate_unique_secure_token
So, it's why I use this trick

2021-07-02 21:20 UTC, Alexey1100 commented on app/models/invite.rb
>    has_secure_token
Ahh okay, looks like it was added in rails 6.1.
https://github.com/rails/rails/commit/51443e22f3cba76907204cc528ebab43224adfd9

We should probably upgrade since it was released more than a half of year ago, but yeah it's out of scope for this PR.

2021-07-02 21:23 UTC, Alexey1100 commented on app/models/invite.rb
> +  def self.generate_unique_secure_token
Okay, maybe better to update the spec to verify that the `invite#token` is actually populated on creation with the right value, and add a comment that it's an override of default method, because it's a bit unclear now.

2021-07-05 15:25 UTC, Alexey1100 approved these changes

2021-07-06 17:07 UTC, merged