Wallet changes for nil blockchain
CoMakery/comakery-server pull request #2226
Opened 2021-07-06 14:04 UTC by sofiyareverse

https://www.pivotaltracker.com/n/projects/2167210/stories/177956343

Actually, I have some questions, how could it be reproduced. But for now as I have understood It can apply null address if it has ore_id, so blockchain address validation will not fail.  As the result we will knock to blockchain_supported_by_ore_id method and after that we will have an error with blockchain - method `supported_by_ore_id?' for nil:NilClass. Am I right?

2021-07-06 16:13 UTC, Riddlerrr commented
@sofiyareverse  Blockchain is mandatory field for an Wallet and there are no Wallets without blockchain filled on demo:
```
> Wallet.where(_blockchain: nil).count
=> 0
```

So I think the issue should be somewhere else

2021-07-06 16:29 UTC, Alexey1100 commented
Yep, the error is raised when we trying to create a wallet.
I remember that at some point we are converting user provided param `blockchain` into internal enum `_blockchain`, so probably in some cases validation is triggered before we perform the conversion.

2021-07-07 16:17 UTC, Riddlerrr requested changes

2021-07-07 16:17 UTC, Riddlerrr commented on spec/acceptance/api/v1/19_wallets_spec.rb
> +      example 'CREATE WALLET – ORE_ID WITH PROVISIONING – ERROR' do
These acceptance tests need for docs generation, so if you don't want to show something in docs it should be placed in usual controller tests.
I think we already have example with an error, so let's move into controller tests.

2021-07-09 10:46 UTC, zhinfuhnya commented on spec/controllers/api/v1/wallets_controller_spec.rb
> +        token = create(:asa_token)
It's a bad practice to create examples inside `it` scope.

2021-07-09 17:15 UTC, Riddlerrr approved these changes

2021-07-09 17:15 UTC, merged