Project tasks visibility
CoMakery/comakery-server pull request #2227
Opened 2021-07-06 15:06 UTC by zhinfuhnya

https://www.pivotaltracker.com/n/projects/2167210/stories/178336397

2021-07-06 16:33 UTC, Alexey1100 commented on app/controllers/award_types_controller.rb
> +  rescue_from Pundit::NotAuthorizedError, with: :not_authorized
We have the same code in ApplicationController, which should be inherited here.
Is it not working?

2021-07-06 18:43 UTC, Alexey1100 requested changes
According to ticket the logic should only apply to whitelabel env.

In the non-whitelabel env the page should be accessible regardless the project mission settings, also given that the mission there is optional.

2021-07-06 18:43 UTC, Alexey1100 commented on app/javascript/components/layouts/Header.jsx
> +        { projectAwardsVisible &&
Should always display on non-whitelabel.

2021-07-06 18:43 UTC, Alexey1100 commented on app/policies/award_policy.rb
> +    @project.mission&.project_awards_visible?
Will not work properly in non-whitelabel env.

2021-07-06 18:43 UTC, Alexey1100 commented on app/policies/award_type_policy.rb
> +    @project.mission&.project_awards_visible?
Will not work properly in non-whitelabel env.

2021-07-06 18:43 UTC, Alexey1100 commented on app/policies/award_policy.rb
> +    @project.mission&.project_awards_visible?
We should always display the page there, regardless mission.

2021-07-06 18:43 UTC, Alexey1100 commented on app/policies/project_policy.rb
> +    (show? || unlisted?) && project.mission&.project_awards_visible?
Will not work properly in non-whitelabel env.

2021-07-06 18:43 UTC, Alexey1100 commented on db/migrate/20210706104324_add_project_awards_visible_to_missions.rb
> +    add_column :missions, :project_awards_visible, :boolean, default: false
Needs `null: false`

2021-07-06 18:43 UTC, Alexey1100 commented on app/controllers/award_types_controller.rb
> +  rescue Pundit::NotAuthorizedError
Still not sure why we are adding it here, instead of relying on default auth rescue in ApplicationController : )

2021-07-06 18:43 UTC, Alexey1100 commented on spec/features/award_types/index_spec.rb
> +      let(:mission) { create :mission, project_awards_visible: false }
This logic should only be triggered with a whitelabel mission.

2021-07-06 21:48 UTC, zhinfuhnya commented on app/javascript/components/layouts/Header.jsx
> +        { projectAwardsVisible &&
So, if the mission isn't a `whitelabel` we shouldn't display `My Tasks`?

2021-07-06 21:51 UTC, zhinfuhnya commented on app/policies/award_policy.rb
> +    @project.mission&.project_awards_visible?
Why it shouldn't work in the case of a non-whitelabel mission?

2021-07-06 21:52 UTC, zhinfuhnya commented on app/policies/award_type_policy.rb
> +    @project.mission&.project_awards_visible?
https://github.com/CoMakery/comakery-server/pull/2227#discussion_r664901098

2021-07-06 21:52 UTC, zhinfuhnya commented on app/policies/project_policy.rb
> +    (show? || unlisted?) && project.mission&.project_awards_visible?
https://github.com/CoMakery/comakery-server/pull/2227#discussion_r664901098

2021-07-06 21:54 UTC, zhinfuhnya commented on app/controllers/award_types_controller.rb
> +  rescue Pundit::NotAuthorizedError
Regarding to requirements:

`Then I should not see "My Tasks" in the site navigation
And when I visit /tasks then I should be redirected to /projects
When I visit a project at /projects/:id
And I should not see the project "tasks" menu
And when I visit /projects/:id/batches then I should be redirected to the 404 error page
`

We must have unique fallback paths for each case. We can't rely on default rescue path (`root_path`).

2021-07-06 21:57 UTC, zhinfuhnya commented on spec/features/award_types/index_spec.rb
> +      let(:mission) { create :mission, project_awards_visible: false }
Thus we consider that the changes will only be relative to whitelabel mission (in the case of a non-whitelabel we always display tasks)?

2021-07-07 00:34 UTC, Alexey1100 commented on app/policies/award_policy.rb
> +    @project.mission&.project_awards_visible?
Mission is not required for non-whitelabel projects, so in this case it will return false and page would not be displayed.

2021-07-07 00:35 UTC, Alexey1100 commented on app/controllers/award_types_controller.rb
> +  rescue Pundit::NotAuthorizedError
I think it's typo :)
We have default redirect to root when not-authorised

cc @aquabu

2021-07-07 00:39 UTC, Alexey1100 commented on app/controllers/award_types_controller.rb
> +  rescue Pundit::NotAuthorizedError
Considering it's a fail-state and user shouldn't be ever following this url, I think it's better to just rely on default behaviour across the website.

2021-07-13 03:49 UTC, Alexey1100 requested changes
I think we can make it much simpler :)

2021-07-13 03:49 UTC, Alexey1100 commented on app/javascript/components/layouts/ProjectSetupHeader.jsx
> +                (project.whitelabel && project.projectAwardsVisible)) &&
Looks like something is wrong here.

We are checking that project **is not whitelabel** AND (token is not lockup OR project **is whitelabel** ...)

2021-07-13 03:49 UTC, Alexey1100 commented on config/database.yml
> -  database: <%= ENV["DATABASE"] || Rails.application.config.project_slug + '_development_' + branch %>
This shouldn't be checked in :)

2021-07-13 03:49 UTC, Alexey1100 commented on app/controllers/award_types_controller.rb
> +    raise Pundit::NotAuthorizedError unless policy_scope.index?
I think this should be:

```ruby
authorize @project, :show_award_types?
```

While project policy should be:

```ruby
def show_award_types?
  (show? || unlisted?) && (!whitelabel || mission.project_awards_visible?)
end
```

2021-07-13 03:49 UTC, Alexey1100 commented on app/policies/project_policy.rb
> +    show? || unlisted?
```ruby
def show_award_types?
  (show? || unlisted?) && (!whitelabel || mission.project_awards_visible?)
end
```

(See comment above)

2021-07-13 03:49 UTC, Alexey1100 commented on app/controllers/awards_controller.rb
> +    policy_scope = AwardPolicy::Scope.new(current_account, Award, @whitelabel_mission)
We shouldn't use scope to authorise an action, but to define a collection based on account.

Since we don't have any particular instance here to initialise the policy, I think the solution would be something like:

```ruby
raise Pundit::NotAuthorizedError if (whitelabel_mission && !@whitelabel_mission.project_awards_visible?)
```

2021-07-13 03:49 UTC, Alexey1100 commented on app/policies/award_policy.rb
> +    end
Scope shouldn't be used for authorisation.
See comment above.

2021-07-13 03:49 UTC, Alexey1100 commented on app/policies/award_policy.rb
> +    def initialize(account, scope, whitelabel_mission = nil)
whitelabel_mission is not needed here

2021-07-13 03:49 UTC, Alexey1100 commented on app/policies/award_type_policy.rb
> +    def index?
Same here, scope should not define auth logic.

2021-07-13 03:49 UTC, Alexey1100 commented on app/policies/award_type_policy.rb
> +    def initialize(account, project, whitelabel_mission, scope)
It makes whitelabel_mission not needed here.

2021-07-13 14:51 UTC, zhinfuhnya commented on app/controllers/awards_controller.rb
> +    policy_scope = AwardPolicy::Scope.new(current_account, Award, @whitelabel_mission)
Heh, regarding to previous conversation we decided auth action with scope and move `whitelabel` inside policy 🤪

https://comakery-inc.slack.com/archives/C01HNM6JYGM/p1625855765158200

2021-07-13 14:54 UTC, zhinfuhnya commented on app/javascript/components/layouts/ProjectSetupHeader.jsx
> +                (project.whitelabel && project.projectAwardsVisible)) &&
The mission has a `project_awards_visible` switch, which means that if it is a whitelabel and the awards are visible, we display the link.

2021-07-13 14:54 UTC, zhinfuhnya commented on config/database.yml
> -  database: <%= ENV["DATABASE"] || Rails.application.config.project_slug + '_development_' + branch %>
🙃

2021-07-14 19:03 UTC, Alexey1100 requested changes

2021-07-14 19:03 UTC, Alexey1100 commented on app/controllers/awards_controller.rb
> +    authorize(@project, :show_whitelabel_awards?) if @whitelabel_mission.present?
Hmm, we don't have @project here.

```ruby
before_action :set_project, except: %i[index confirm]
```

It should just check whether @whitelabel_mission is present and allows the awards.

2021-07-14 19:03 UTC, Alexey1100 commented on app/controllers/awards_controller.rb
> +    authorize(@project, :show_whitelabel_awards?) if @whitelabel_mission.present?
Specs are passing, so looks like this part is not covered.

2021-07-15 09:50 UTC, zhinfuhnya commented on app/controllers/awards_controller.rb
> +    authorize(@project, :show_whitelabel_awards?) if @whitelabel_mission.present?
https://github.com/CoMakery/comakery-server/pull/2227/commits/0c0420b510f063e73650204d8528ed73eb8de27a

2021-07-15 17:56 UTC, Alexey1100 requested changes

2021-07-15 17:56 UTC, Alexey1100 commented on app/controllers/awards_controller.rb
> +  before_action :unavailable_for_whitelabel, except: [:index]
Ohh right, looks like we need to remove this callback completely from here.
Otherwise user would not be able to start/submit a task.

2021-07-16 16:05 UTC, Alexey1100 approved these changes

2021-07-16 16:52 UTC, merged