add html proofer with patch
CoMakery/comakery-server pull request #2231
Opened 2021-07-07 09:32 UTC by o-bahriy

https://www.pivotaltracker.com/story/show/178795249

2021-07-07 10:36 UTC, zhinfuhnya commented on config/application.rb
> +    config.middleware.use HTMLProofer::Middleware if Rails.env.development?
Better to reduce to one line:
config.middleware.use HTMLProofer::Middleware if Rails.env.development? || Rails.env.test?

: )

2021-07-11 16:23 UTC, Alexey1100 commented on app/views/accounts/index.html.erb
> -              <%= turbo_frame_tag "mission_#{@whitelabel_mission&.id}_account_wallets" do %>
Apparently, there was nothing wrong with html-proofer setup.
Html spec requires `table` to have all child elements to be inside `tr`, so I've moved turbo stream tag out of the table.

Turbo frame tag is not needed here as well, as it's only required when HTTP response triggered from the page includes turbo frames and we want to modify content wrapped in the tag. We are using turbo streams here, so no turbo frames needed.

2021-07-13 14:48 UTC, zhinfuhnya requested changes

2021-07-13 14:48 UTC, zhinfuhnya commented on app/views/accounts/index.html.erb
> -              <%= turbo_frame_tag "mission_#{@whitelabel_mission&.id}_account_wallets" do %>
it is necessary to revert the turbo frame.

2021-07-13 17:26 UTC, zhinfuhnya approved these changes

2021-07-14 04:04 UTC, aquabu approved these changes

2021-07-14 04:04 UTC, merged