Update the vertical styling: styleguide page
CoMakery/comakery-server pull request #2242
Opened 2021-07-12 11:54 UTC by sofiyareverse

https://www.pivotaltracker.com/n/projects/2167210/stories/178778213

2021-07-13 03:19 UTC, Alexey1100 requested changes

2021-07-13 03:19 UTC, Alexey1100 commented on app/javascript/packs/application.js
>  // import '../src/dist/css/tabler.min.css'
We can remove this now

2021-07-13 03:19 UTC, Alexey1100 commented on app/javascript/packs/application.js
>  import '../src/dist/css/upside-vendors.css'
And this one

2021-07-13 03:19 UTC, Alexey1100 commented on app/views/layouts/_header_new_styling.html.erb
> +              Projects
Looks like we are missing some code here which indicates current page.

2021-07-13 03:19 UTC, Alexey1100 commented on app/views/layouts/_header_new_styling.html.erb
> +        <li class="nav-item">
We should add `active` class here, when current page matches the nav bar item url.

2021-07-13 10:59 UTC, sofiyareverse commented on app/javascript/packs/application.js
>  // import '../src/dist/css/tabler.min.css'
But why?

2021-07-14 16:31 UTC, Alexey1100 commented on app/javascript/packs/application.js
>  // import '../src/dist/css/tabler.min.css'
Tabler migration is ready :)

2021-07-15 18:23 UTC, Alexey1100 commented on app/javascript/controllers/vertical-navbar_controller.js
> +    Handbar.addEventListener('click', (event) => {
Minor issue, but could you implement this with stimulus approach (using targets and actions).
Would be easier to maintain and test :)

Ref: https://stimulus.hotwired.dev/handbook/building-something-real

2021-07-16 16:16 UTC, Alexey1100 commented on app/javascript/packs/application.js
> +import 'packs/new_styling'
Should be in `../src/new_styling`

2021-07-16 16:34 UTC, Alexey1100 commented
Good job :)
A couple of minor styling issues, which should be easy to fix:

1. Dropdown icon is missing:
<img width="314" alt="Screenshot 2021-07-16 at 19 23 07" src="https://user-images.githubusercontent.com/10757562/125979469-ecf763ce-1c3d-44e8-86ae-2c080e1505c2.png">

2. Mouse hover highlight is missing for first-level menu (present in organisation menu):
<img width="385" alt="Screenshot 2021-07-16 at 19 19 25" src="https://user-images.githubusercontent.com/10757562/125979702-8db808d8-df38-4eec-8449-d9c9a56f37a2.png">

3. Wallets icon is not centered with other icons:
<img width="217" alt="Screenshot 2021-07-16 at 19 24 29" src="https://user-images.githubusercontent.com/10757562/125979769-cedd931d-db27-4e12-a46b-b41c8446ecbc.png">

4. Icons are not the same color as font:
<img width="233" alt="Screenshot 2021-07-16 at 19 25 18" src="https://user-images.githubusercontent.com/10757562/125979998-b31e270b-8252-4810-8240-f591a6d7b0f3.png">
<img width="439" alt="Screenshot 2021-07-16 at 19 32 24" src="https://user-images.githubusercontent.com/10757562/125980012-f1eb2b13-57af-48ef-9c51-10379743c704.png">


5. Mobile menu has some broken margins:
<img width="409" alt="Screenshot 2021-07-16 at 19 26 25" src="https://user-images.githubusercontent.com/10757562/125980056-46fa43d5-8835-4f89-96df-c76e9963d74b.png">
<img width="424" alt="Screenshot 2021-07-16 at 19 26 32" src="https://user-images.githubusercontent.com/10757562/125980080-0edf3dc0-38f8-4f4d-bc2b-d6c4101a37aa.png">

2021-07-20 19:06 UTC, Alexey1100 requested changes
Some UI issues:

1. Organization menu is missing:
<img width="367" alt="Screenshot 2021-07-20 at 22 01 33" src="https://user-images.githubusercontent.com/10757562/126381194-8174bc7e-daf7-49f1-8de2-bae3e096f717.png">

2. Close button is not aligned properly, Logo is not centered
<img width="367" alt="Screenshot 2021-07-20 at 22 01 33" src="https://user-images.githubusercontent.com/10757562/126381267-fc6177c6-017c-462e-a75a-29c9b2c99d85.png">

2021-07-20 21:17 UTC, Alexey1100 commented
Good!

I've noticed one more little issue.
The elements are highlighted correctly, but links actually work only if you click on text or icon, so it's a bit confusing.

https://user-images.githubusercontent.com/10757562/126396441-189daba8-ac2f-45b8-95da-d49ef5d31725.mov

2021-07-20 21:39 UTC, Alexey1100 commented
And I think we should add a feature spec, which will open the page and verify:

1) All links are present and work correctly for every case (unauthorised user / authorised user / authorised comakery admin) both in collapsed and full state.
2) Collapsed state is preserved in local storage between visits.

2021-07-21 07:01 UTC, sofiyareverse commented
> And I think we should add a feature spec, which will open the page and verify:
> 
> 1. All links are present and work correctly for every case (unauthenticated user / authenticated user / authenticated comakery admin) both in collapsed and full state.
>    Pls also note and test the recent Tasks menu visibility updates for whitelabel – [Project tasks visibility #2227](https://github.com/CoMakery/comakery-server/pull/2227) and that the Organization menu currently should not be visible in whitelabel.
> 2. Collapsed state is preserved in local storage between visits.

To my mind it will be a good idea only after implementing it to the each page because this page will not exist

2021-07-21 09:53 UTC, Alexey1100 commented
Let's add it :)
Switching the spec later to any existing page wouldn't be a big deal, and it's really time consuming to verify all of these cases manually during the review.

2021-07-21 15:37 UTC, zhinfuhnya approved these changes

2021-07-26 07:42 UTC, Alexey1100 requested changes

2021-07-26 07:42 UTC, Alexey1100 commented on app/views/layouts/_header_new_styling.html.erb
> +                  Tasks
Pls integrate Tasks visibility changes from #2227

2021-07-26 13:52 UTC, Alexey1100 requested changes

2021-07-26 13:52 UTC, Alexey1100 commented on app/views/layouts/_header_new_styling.html.erb
> +          <% if @whitelabel_mission.present? && @whitelabel_mission.project_awards_visible? %>
Should display Tasks if `@whitelabel_mission` is not present or `@whitelabel_mission.project_awards_visible?`

Pls refer to current logic :)

2021-07-26 17:28 UTC, Alexey1100 approved these changes

2021-07-27 17:08 UTC, merged