Add project vertical navbar
CoMakery/comakery-server pull request #2243
Opened 2021-07-12 14:07 UTC by sofiyareverse

2021-07-28 16:45 UTC, Alexey1100 requested changes
Visibility of project nav tabs should be based on policies, project settings and token type.
Pls see current implementation of `ProjectSetupHeader.jsx` for the references.

General notes are:
- All of the links should be rendered based on according project policy
- Transfer Rules are only visible for projects using security token
- Tasks page availability should be based on whitelabel settings 
- Project overview shouldn't be available on whitelabel

P.s: should we include external project links, like wiki and GitHub? cc @aquabu

2021-07-29 16:40 UTC, Alexey1100 requested changes
Pls use according policy for each nav element.

2021-07-29 16:40 UTC, Alexey1100 commented on app/views/shared/_project_new_styling.html.erb
> +        <% if @whitelabel_mission&.project_awards_visible? || !@whitelabel_mission %>
Should be:

```ruby
policy(@project).show_award_types? && (@whitelabel_mission&.project_awards_visible? || !@whitelabel_mission)
```

2021-07-29 16:40 UTC, Alexey1100 commented on app/views/shared/_project_new_styling.html.erb
> +        <li class="nav-item <%= active_class(project_dashboard_transfers_path(@project.id)) %>">
Should check for:

```ruby
policy(@project).show_contributions?
```

2021-07-29 16:40 UTC, Alexey1100 commented on app/views/shared/_project_new_styling.html.erb
> +          <a class="nav-link" href="/projects/<%= @project.id %>/dashboard/accounts">
Should check for:

```ruby
policy(@project).show_contributions?
```

2021-07-29 16:40 UTC, Alexey1100 commented on app/views/shared/_project_new_styling.html.erb
> +        <% if current_account&.owned_project?(@project) || !@project.require_confidentiality %>
Should use policy:

```ruby
policy(@project).show_transfer_rules?
```

2021-07-29 16:40 UTC, Alexey1100 commented on app/views/shared/_project_new_styling.html.erb
> +        <% if current_account&.owned_project?(@project) %>
Should use policy:

```ruby
policy(@project).accesses?
```

2021-07-29 16:40 UTC, Alexey1100 commented on app/views/shared/_project_new_styling.html.erb
> +          <li class="nav-item <%= active_class(edit_project_path(@project.id)) %>">
Should use policy:

```ruby
policy(@project).edit?
```

2021-07-30 17:27 UTC, Alexey1100 requested changes
@sofiyareverse great job!

The icons and fonts looks a bit larger than they should, could you fix that?
Also non-collapsed view shouldn't include icons.


https://user-images.githubusercontent.com/10757562/127689824-d8a5b33a-01d2-4904-a06d-f1cd82e97c0c.mov

2021-07-30 18:18 UTC, sofiyareverse commented
> @sofiyareverse great job!
> 
> The icons and fonts looks a bit larger than they should, could you fix that?
> Also non-collapsed view shouldn't include icons.
> 
>  Screen.Recording.2021-07-30.at.20.22.27.mov

I could but if you look to figma pictures you 'll that there are large pictures for the project nav

2021-08-03 11:28 UTC, zhinfuhnya approved these changes

2021-08-04 05:09 UTC, Alexey1100 approved these changes

2021-08-04 05:36 UTC, merged