Update transfers csv columns
CoMakery/comakery-server pull request #2246
Opened 2021-07-13 10:06 UTC by zhinfuhnya

https://www.pivotaltracker.com/n/projects/2167210/stories/178562909

2021-07-13 16:33 UTC, Riddlerrr requested changes

2021-07-13 16:33 UTC, Riddlerrr commented on app/decorators/award_decorator.rb
> +      transaction_hash,
is can be just: `latest_blockchain_transaction&. tx_hash`

2021-07-14 16:32 UTC, Riddlerrr approved these changes

2021-07-14 16:32 UTC, Riddlerrr commented on app/decorators/award_decorator.rb
> +      paid? ? ethereum_transaction_address : nil,
I think it's ok to use just `ethereum_transaction_address` without conditions

2021-07-14 16:40 UTC, zhinfuhnya commented on app/decorators/award_decorator.rb
> +      paid? ? ethereum_transaction_address : nil,
@Riddlerrr regarding to requirements need display address only if transfer is paid.

2021-07-14 17:13 UTC, Alexey1100 commented on app/decorators/award_decorator.rb
> +      paid? ? ethereum_transaction_address : nil,
Yep, otherwise it would be displayed for failed tx as well

2021-07-14 18:33 UTC, Alexey1100 requested changes

2021-07-14 18:33 UTC, Alexey1100 commented on app/decorators/award_decorator.rb
> +      account&.email,
There's an edge case when award is issued to an email address, without an account.

I think it should be:

```ruby
account&.email || email
```

2021-07-15 17:05 UTC, Alexey1100 approved these changes

2021-07-15 17:05 UTC, merged