WIP: Intoduce BlockchainTransactionQuery
CoMakery/comakery-server pull request #2247
Opened 2021-07-13 12:47 UTC by Riddlerrr

2021-07-15 18:42 UTC, Alexey1100 commented on spec/controllers/api/v1/blockchain_transactions_controller_spec.rb
> +      let!(:project) { create(:project, token: create(:lockup_token, batch_contract_address: build(:ethereum_address_1)), transfer_batch_size: transfer_batch_size) }
We don't need `batch_contract_address` for lockup token.
Is it not working without it?

🤔

2021-07-16 00:09 UTC, Alexey1100 commented on app/queries/next_blockchain_transactables.rb
> +    q.limit(batch_size)
Looks like these lines (66-68) should be only applicable for awards.

2021-07-16 00:11 UTC, Alexey1100 commented on app/queries/next_blockchain_transactables.rb
> +          (tokens.batch_contract_address IS NOT NULL) OR
Should verify here that token type is erc20.

2021-07-16 00:20 UTC, Alexey1100 commented on app/queries/next_blockchain_transactables.rb
> +      !project.hot_wallet_disabled? && transactable_class != TransferRule
I think better to make it more readable, just leaving:

```ruby
def hot_wallet_support?(transactable_class)
  transactable_class != TransferRule
end
```

And inside `call` we can use:
```ruby
next if target_hot_wallet? && hot_wallet_disabled?
next if target_hot_wallet? && !hot_wallet_support?(transactable_class)
```

2021-07-16 00:24 UTC, Alexey1100 commented on app/queries/next_blockchain_transactables.rb
> +      transactable_class == Award && project.transfer_batch_size > 1 && project.token.batch_contract_address.present?
Or token type is `:token_release_schedule`

2021-07-16 00:27 UTC, Alexey1100 commented on spec/queries/next_blockchain_transactables_spec.rb
> +    let(:call) { described_class.new(project: project, target: { for: :hot_wallet }, verified_accounts_only: false).call }
Looks like this line is not used

2021-07-16 00:29 UTC, Alexey1100 commented on spec/queries/next_blockchain_transactables_spec.rb
> +            is_expected.to eq [award1, award2]
Better use `.to match_array` to avoid flakiness.

2021-07-16 00:38 UTC, Alexey1100 commented on spec/queries/next_blockchain_transactables_spec.rb
> +    end
Looks like it needs more coverage for cancelled/failed transactions, as well as TransferRules and AccountTokenRecords, since logic there is a bit different.

2021-07-16 06:42 UTC, Riddlerrr commented on spec/controllers/api/v1/blockchain_transactions_controller_spec.rb
> +      let!(:project) { create(:project, token: create(:lockup_token, batch_contract_address: build(:ethereum_address_1)), transfer_batch_size: transfer_batch_size) }
Yeah, it must work, checking...

2021-07-16 07:09 UTC, Riddlerrr commented on spec/controllers/api/v1/blockchain_transactions_controller_spec.rb
> +      let!(:project) { create(:project, token: create(:lockup_token, batch_contract_address: build(:ethereum_address_1)), transfer_batch_size: transfer_batch_size) }
fixed

2021-07-16 07:40 UTC, Riddlerrr commented on app/queries/next_blockchain_transactables.rb
> +      !project.hot_wallet_disabled? && transactable_class != TransferRule
I agree. Initially it was like this but it add cyclomatic complexity and rubocop was not happy =)
Ok, let's ignore rubocop

2021-07-16 07:51 UTC, Riddlerrr commented on app/queries/next_blockchain_transactables.rb
> +    q.limit(batch_size)
👍 Moved it into scopes_for_awards

2021-07-16 16:09 UTC, Alexey1100 commented on app/queries/next_blockchain_transactables.rb
> +      !project.hot_wallet_disabled? && transactable_class != TransferRule
Yeah, or we can just extract these two checks into a separate method like `should_be_processed?`

2021-07-20 20:19 UTC, Alexey1100 requested changes

2021-07-20 20:19 UTC, Alexey1100 commented on spec/factories/tokens.rb
> +      token_frozen { false }
Looks like this line is not needed here

2021-07-20 20:19 UTC, Alexey1100 commented on app/queries/next_blockchain_transactables.rb
> +        project.token.public_send(transactable_class.table_name)
Will not work properly with `Token` transactable, which is used for token freeze

2021-07-20 20:19 UTC, Alexey1100 commented on spec/factories/accounts.rb
> +      verifications { [association(:verification, passed: false)] }
I think it makes sense to call it `verification_failed`, since unverified is default state when verification doesn't exist.

2021-07-20 20:19 UTC, Alexey1100 commented on spec/queries/next_blockchain_transactables_spec.rb
> +end
Looks like we need coverage for Token freeze as well here, since this logic is now used everywhere.

Also could you go through UI with both Metamask/WalletConnect and OREID, and verify that Transfers, AccountTokenRecords, TransferRules (creation/deletion) and Token freeze is not broken, since we don't have tests for that.

2021-07-20 20:30 UTC, Alexey1100 commented on spec/queries/next_blockchain_transactables_spec.rb
> +end
You can use the project currently present in seeds for testing:
` FactoryBot.create :project, :using_security_token, account: Account.first`

Let me know if you need permissions for the security token it's using.

2021-07-21 13:40 UTC, zhinfuhnya approved these changes
👨‍🚀 🙆‍♂️ 🚀 💫

2021-07-21 13:40 UTC, zhinfuhnya commented on app/controllers/api/v1/blockchain_transactions_controller.rb
> +    if transactable.any?
As far as I understand `NextBlockchainTransactables` returns relation, in order to it better to use plural name.

2021-07-21 13:40 UTC, zhinfuhnya commented on app/queries/next_blockchain_transactables.rb
> +      transactable_class.in?([Award, AccountTokenRecord])
`transactable_class.in?(default_transactable_classes)`

2021-07-22 08:36 UTC, Riddlerrr commented on app/models/concerns/blockchain_transactable.rb
> +      NextBlockchainTransactables.new(project: project, target: :manual, transactable_classes: [Award]).call
Let's just delete it  =)

2021-07-22 10:47 UTC, Riddlerrr commented on app/queries/next_blockchain_transactables.rb
> +      transactable_class.in?([Award, AccountTokenRecord])
for now it is equal, yes but they can be different in a future and it is not related. So let's leave it as is

2021-07-26 07:24 UTC, Alexey1100 requested changes

2021-07-26 07:24 UTC, Alexey1100 commented on app/queries/next_blockchain_transactables.rb
> +    return Token.where(id: project.token_id) if transactable_class == Token
This line and...

2021-07-26 07:24 UTC, Alexey1100 commented on app/queries/next_blockchain_transactables.rb
> +        project.token
...this one seem to be repeating each other

2021-07-26 10:55 UTC, Alexey1100 approved these changes

2021-07-26 16:47 UTC, merged