Transfer settings menu
CoMakery/comakery-server pull request #2248
Opened 2021-07-13 14:33 UTC by zhinfuhnya

https://www.pivotaltracker.com/story/show/178544187

2021-07-14 16:29 UTC, Riddlerrr approved these changes
👍

2021-07-14 18:52 UTC, Alexey1100 requested changes

2021-07-14 18:52 UTC, Alexey1100 commented on app/views/dashboard/transfers/_transfer.html.erb
> +                       src="<%= project_transfer_settings_path(transfer_id: transfer.id) %>">
Oh looks like it's not in the ticket, but we discussed that before.

The important part is to make the menu lazy load each time, similar to transfer form, so the prioritise button will be always up-to-date.

I've added the details in the ticket.

2021-07-15 17:06 UTC, Alexey1100 approved these changes

2021-07-15 17:07 UTC, merged