Optimize transfers page
CoMakery/comakery-server pull request #2252
Opened 2021-07-15 15:02 UTC by zhinfuhnya

2021-07-20 16:32 UTC, Riddlerrr approved these changes
👍

2021-07-20 16:32 UTC, Riddlerrr commented on app/views/dashboard/transfers/_chart.html.erb
> +                  <% percentage = @unfiltered_transfers.size == 0 ? 0 : ((type_count.to_f / @unfiltered_transfers.size.to_f) * 100).to_i %>
```suggestion
                  <% percentage = @unfiltered_transfers.size.zero? ? 0 : ((type_count.to_f / @unfiltered_transfers.size.to_f) * 100).to_i %>
```

2021-07-20 21:01 UTC, Alexey1100 requested changes
A couple of minor issues:

2021-07-21 07:22 UTC, zhinfuhnya commented on app/models/award.rb
> +  before_validation :set_paid_status_if_project_has_no_token, if: -> { status == 'accepted' && !project&.token }
Yes

2021-07-23 11:30 UTC, Alexey1100 commented on app/models/award.rb
> +  before_validation :set_paid_status_if_project_has_no_token, if: -> { status == 'accepted' && !project&.token }
Let's keep it raising if project is not present, otherwise we might end up marking award as paid when running the validation in a wrong moment.

There shouldn't be any cases where we perform the validation without knowing the project id.

2021-07-23 16:56 UTC, Alexey1100 approved these changes

2021-07-23 16:59 UTC, merged