Remove experiences, specialties and interests
CoMakery/comakery-server pull request #2267
Opened 2021-07-22 11:07 UTC by zhinfuhnya

https://www.pivotaltracker.com/n/projects/2167210/stories/178964759

2021-07-22 11:09 UTC, zhinfuhnya commented
@aquabu @Alexey1100 should we adapt the specialties to the roles of the project participants?

2021-07-27 16:26 UTC, Riddlerrr commented on .overcommit.yml
> -# Hooks that run after HEAD changes or a file is explicitly checked out.
I believe it was committed accidentally

2021-07-27 16:36 UTC, Riddlerrr requested changes
Please fix a failed specs

2021-07-28 16:26 UTC, Alexey1100 requested changes

2021-07-28 16:26 UTC, Alexey1100 commented on app/controllers/application_controller.rb
> +      mission: {
Possible conflict with #2284

2021-07-28 16:26 UTC, Alexey1100 commented on app/controllers/missions_controller.rb
> +    def set_mission_props # rubocop:todo Metrics/CyclomaticComplexity
I don't think we need it after #2264

2021-07-28 16:26 UTC, Alexey1100 commented on app/javascript/components/MyTask.jsx
>                    </Type>
I think we should remove the type, since it just indicates the specialty which is no longer present.

2021-07-28 16:26 UTC, Alexey1100 commented on app/models/award.rb
> +  # TODO: Should we remove assignments?
Nope, it's different logic :)

2021-07-28 16:26 UTC, Alexey1100 commented on public/doc/api/v1/index.html
> -        <a href="/doc/api/v1/vii._blockchain_transactions/generate_transaction_–_transactable_type_and_transactable_id.html">GENERATE TRANSACTION – TRANSACTABLE TYPE AND TRANSACTABLE ID</a>
These links shouldn't be removed

2021-07-28 16:26 UTC, Alexey1100 commented on public/doc/api/v1/vii._blockchain_transactions/generate_transaction.html
> -<html>
These and any other docs should't be removed

2021-07-29 20:49 UTC, Alexey1100 approved these changes

2021-07-30 16:18 UTC, Riddlerrr reviewed
It's pretty big changes, so maybe we should extract migrations to a separate PR and ensure we don't break anything before deleting data?

cc @Alexey1100 @aquabu

2021-08-02 16:29 UTC, Riddlerrr commented on db/data_migrations/20210426121452_fill_roles_with_interests.rb
> -class FillRolesWithInterests < ActiveRecord::DataMigration
This file was not reverted

2021-08-02 16:30 UTC, Riddlerrr commented on spec/data_migrations/fill_roles_with_interests_spec.rb
> -require 'rails_helper'
And this

2021-08-02 16:35 UTC, Riddlerrr commented on db/data_migrations/20210426121452_fill_roles_with_interests.rb
> -class FillRolesWithInterests < ActiveRecord::DataMigration
Oh.. it will not work anyway because Interest was deleted

2021-08-02 16:35 UTC, Riddlerrr approved these changes

2021-08-02 18:10 UTC, zhinfuhnya commented on db/data_migrations/20210426121452_fill_roles_with_interests.rb
> -class FillRolesWithInterests < ActiveRecord::DataMigration
No, you're right : )

It's also need to be reverted.

2021-08-03 16:51 UTC, merged