Convert CoffeeScript to ES6 and remove unused JS
CoMakery/comakery-server pull request #2281
Opened 2021-07-27 15:02 UTC by zhinfuhnya

https://www.pivotaltracker.com/n/projects/2167210/stories/178778386

2021-07-28 16:13 UTC, Alexey1100 requested changes

2021-07-28 16:13 UTC, Alexey1100 commented on app/javascript/packs/application.js
> +import '../src/dist/css/upside.css'
We are not using `upside.css` anymore.

2021-07-28 16:13 UTC, Alexey1100 commented on app/javascript/packs/application.js
> +import '../src/dist/css/upside.css'
We are not using `upside.css` anymore.

2021-07-29 15:57 UTC, Riddlerrr approved these changes

2021-07-29 17:03 UTC, Alexey1100 approved these changes

2021-07-29 17:06 UTC, merged