Require invitation whitelabel can not see sign up
CoMakery/comakery-server pull request #2291
Opened 2021-07-30 16:46 UTC by sofiyareverse

2021-08-02 16:23 UTC, Riddlerrr requested changes

2021-08-02 16:23 UTC, Riddlerrr commented on spec/features/pages/new_styling_spec.rb
> +      expect(page).not_to have_css('span', text: 'Sign Up')
Let's check for "Sign in" exists before checking for Sign up is not there. To ensure page loaded correctly.

2021-08-02 16:46 UTC, sofiyareverse commented on spec/features/pages/new_styling_spec.rb
> +      expect(page).not_to have_css('span', text: 'Sign Up')
for now we can not do this. It will exist if we have navbar on login page because for now navbar is only on styleguide page before the merge. after the merge it will be seen on session_new_path... and tests will be changed also for pages

2021-08-03 07:29 UTC, Riddlerrr approved these changes
👍

2021-08-03 16:53 UTC, merged