Bump rails to 6.1.4
CoMakery/comakery-server pull request #2293
Opened 2021-08-02 12:52 UTC by Riddlerrr

task: https://www.pivotaltracker.com/story/show/178775172

2021-08-03 14:56 UTC, Riddlerrr commented
It will work after  getting rid of fortitude. Checked here https://github.com/CoMakery/comakery-server/compare/bump-rails-wo-furtitude?expand=1

2021-08-05 15:55 UTC, zhinfuhnya approved these changes

2021-08-05 16:35 UTC, Alexey1100 requested changes

2021-08-05 16:35 UTC, Alexey1100 commented on app/models/invite.rb
> -  # Override ActiveRecord::SecureToken class method (remove after upgrade to rails 6.1)
Nice :)

2021-08-05 16:35 UTC, Alexey1100 commented on app/models/mission.rb
> +  def published_awards
Why is this moved from a relation into a method?

2021-08-05 16:35 UTC, Alexey1100 commented on app/models/project.rb
> +  def published_awards
And here :)

2021-08-05 17:40 UTC, Alexey1100 approved these changes

2021-08-05 19:33 UTC, aquabu approved these changes

2021-08-05 19:33 UTC, merged