Configure overcommit
CoMakery/comakery-server pull request #2303
Opened 2021-08-04 09:21 UTC by zhinfuhnya

https://www.pivotaltracker.com/n/projects/2167210/stories/178965253

2021-08-04 16:15 UTC, Riddlerrr approved these changes

2021-08-04 16:15 UTC, Riddlerrr commented on .overcommit.yml
> +      - '**/db/structure.sql'
I think we don't have structure.sql, we use `schema.rb` instead, so it can be deleted

2021-08-05 16:22 UTC, Riddlerrr commented
I've also moved rubocop config to default path to project root directory

2021-08-05 16:27 UTC, Alexey1100 requested changes
Interesting, lots of files got autocorrected while config hasn't changed.
Is it working properly?

2021-08-06 14:26 UTC, zhinfuhnya commented
> Interesting, lots of files got autocorrected while config hasn't changed.
> Is it working properly?

@Alexey1100 in my case RuboCop works without autocorrection, it just points to the files that need to be corrected.

2021-08-06 14:28 UTC, Alexey1100 commented
@zhinfuhnya we have changes checked in here which shouldn't be here, because the config hasn't changed.

2021-08-06 14:34 UTC, zhinfuhnya commented
@Alexey1100 Indeed, if I make a change for one line, RuboCop check on the whole file.

2021-08-10 08:15 UTC, Riddlerrr commented
I've updated rubocop_todo file so now it works good.
I've also enabled more checks.

2021-08-13 18:32 UTC, Alexey1100 commented
Seems like what I'm seeing is related to:

https://github.com/sds/overcommit/issues/704

2021-08-13 18:49 UTC, Alexey1100 commented
Fix above is not yet released, so resolved by manually adding `--disable-pending-cops` flag to overcommit rubocop config.

2021-08-13 18:50 UTC, Alexey1100 approved these changes

2021-08-16 17:07 UTC, merged